In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

project_dir = "/content/drive/MyDrive/TISER_Project"
data_dir = f"{project_dir}/data"
results_dir = f"{project_dir}/results"
figures_dir = f"{project_dir}/figures"
notebooks_dir = f"{project_dir}/notebooks"

for d in [project_dir, data_dir, results_dir, figures_dir, notebooks_dir]:
    os.makedirs(d, exist_ok=True)

print("Project folders ready")
print(project_dir)

Project folders ready
/content/drive/MyDrive/TISER_Project

In [ ]:
import json
import os

def save_json(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Saved: {path}")


def load_json(path):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        print(f"Loaded existing file: {path}")
        print("Existing records:", len(data))
        return data

    print("No existing file found. Starting fresh.")
    return []

In [ ]:

# Experiment Configuration
# ================================

EXPERIMENT_NAME = "qwen_baseline_100"

RESULTS_FILE = f"{results_dir}/{EXPERIMENT_NAME}.json"

print("Experiment:", EXPERIMENT_NAME)
print("Results file:", RESULTS_FILE)

Experiment: qwen_baseline_100
Results file: /content/drive/MyDrive/TISER_Project/results/qwen_baseline_100.json

In [ ]:
# Load existing results if they exist
baseline_results_100 = load_json(RESULTS_FILE)

# Resume from where we stopped
start_idx = len(baseline_results_100)

print("Already processed:", start_idx)
print("Will continue from sample:", start_idx)

Loaded existing file: /content/drive/MyDrive/TISER_Project/results/qwen_baseline_100.json
Existing records: 100
Already processed: 100
Will continue from sample: 100

In [ ]:
import zipfile
import json

test_examples = []

test_zip_path = f"{data_dir}/TISER_test.zip"

with zipfile.ZipFile(test_zip_path, "r") as z:
    with z.open("TISER_test.json") as f:
        for line in f:
            test_examples.append(
                json.loads(line.decode("utf-8"))
            )

print("Loaded test examples:", len(test_examples))

Loaded test examples: 22014

In [ ]:
!pip install -q transformers peft accelerate bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 14.5 MB/s eta 0:00:00

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
import torch

base_model_id = "Qwen/Qwen2.5-3B-Instruct"
adapter_id = "arianmo47/de_it_fr_en_mixed_tiser_full_15000_8gb_val_qlora"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

tokenizer = AutoTokenizer.from_pretrained(base_model_id)

base_model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    quantization_config=bnb_config,
    device_map="auto"
)

model = PeftModel.from_pretrained(
    base_model,
    adapter_id
)

model.eval()

print("Fine-tuned Qwen TISER model loaded successfully")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

adapter_config.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

adapter_model.safetensors:   0%|          | 0.00/120M [00:00<?, ?B/s]

Fine-tuned Qwen TISER model loaded successfully

In [ ]:
import re

def normalize_text(text):
    text = text.lower().strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s*,\s*", ", ", text)
    text = text.rstrip(".")
    return text


def extract_answer(response):
    match = re.search(
        r"<answer>\s*(.*?)\s*</answer>",
        response,
        re.DOTALL | re.IGNORECASE
    )

    if match:
        return match.group(1).strip()

    before_reasoning = response.split("<reasoning>")[0].strip()

    if before_reasoning:
        return before_reasoning.split("\n")[0].strip()

    return "NO_ANSWER_FOUND"

print("Utility functions ready")

Utility functions ready

In [ ]:
# Reload existing saved results, if any
baseline_results_100 = load_json(RESULTS_FILE)

start_idx = len(baseline_results_100)

print("Starting from index:", start_idx)

for idx in range(start_idx, 100):

    sample = test_examples[idx]
    prompt = sample["prompt"]

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=400
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    response = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    prediction = extract_answer(response)

    baseline_results_100.append({
        "index": idx,
        "question": sample["question"],
        "ground_truth": sample["answer"],
        "prediction": prediction,
        "full_response": response
    })

    if (idx + 1) % 10 == 0:
        save_json(baseline_results_100, RESULTS_FILE)
        print(f"Processed and saved {idx + 1}/100")

# Final save
save_json(baseline_results_100, RESULTS_FILE)

print("\nBaseline evaluation complete")
print("Total results:", len(baseline_results_100))

Loaded existing file: /content/drive/MyDrive/TISER_Project/results/qwen_baseline_100.json
Existing records: 100
Starting from index: 100
Saved: /content/drive/MyDrive/TISER_Project/results/qwen_baseline_100.json

Baseline evaluation complete
Total results: 100

In [ ]:
correct = 0

for r in baseline_results_100:
    pred = normalize_text(r["prediction"])
    gt = normalize_text(r["ground_truth"])

    if pred == gt:
        correct += 1

print("Correct:", correct)
print("Incorrect:", len(baseline_results_100) - correct)
print("Accuracy:", correct / len(baseline_results_100))

Correct: 49
Incorrect: 51
Accuracy: 0.49

In [ ]:
print(len(baseline_results_100))

print(baseline_results_100[0].keys())

100
dict_keys(['index', 'question', 'ground_truth', 'prediction', 'full_response'])

In [ ]:
print(baseline_results_100[0])

{'index': 0, 'question': 'Which event started first, (Chris Evans was married to Oliver Jensen) or (Chris Evans was born in Bristol, Connecticut)?', 'ground_truth': 'Chris Evans was born in Bristol, Connecticut', 'prediction': 'Chris Evans was born in Bristol,Connecticut', 'full_response': ' Chris Evans was born in Bristol,Connecticut\n\n<reasoning> \nTo determine which event started first, we need to compare the starting times of the two events in question: (Chris Evans was born in Bristol, Connecticut) and (Chris Evans was married to Oliver Jensen). According to the provided temporal context, (Chris Evans was born in Bristol, Connecticut) starts at 1948, while (Chris Evans was married to Oliver Jensen) starts at 1970. Since 1948 is earlier than 1970, it is clear that (Chris Evans was born in Bristol, Connecticut) started first.\n<timeline> \n(Chris Evans was born in Bristol, Connecticut) starts at 1948.\n(Chris Evans was married to Oliver Jensen) starts at 1970.\n</timeline> \n<reflection> \nThe reasoning correctly identifies the starting times of the two events and compares them to determine which one occurred first. There are no apparent errors or improvements needed in this reasoning process.\n</reflection>\n</reasoning>\n<answer>Chris Evans was born in Bristol,Connecticut</answer>'}

In [ ]:
from collections import defaultdict

def get_question_type(question):

    q = question.lower()

    if "started first" in q:
        return "started_first"

    elif "chronological order" in q:
        return "chronological_order"

    elif "how long did" in q:
        return "duration"

    elif "how much time passed" in q:
        return "time_difference"

    elif "when did" in q:
        return "timestamp"

    else:
        return "other"


stats = defaultdict(lambda: {"correct": 0, "total": 0})

for r in baseline_results_100:

    qtype = get_question_type(r["question"])

    stats[qtype]["total"] += 1

    if normalize_text(r["prediction"]) == normalize_text(r["ground_truth"]):
        stats[qtype]["correct"] += 1


for qtype, s in stats.items():

    acc = s["correct"] / s["total"]

    print(f"{qtype}: {s['correct']}/{s['total']} = {acc:.2%}")

started_first: 9/9 = 100.00%
chronological_order: 11/30 = 36.67%
duration: 3/9 = 33.33%
time_difference: 0/9 = 0.00%
timestamp: 9/9 = 100.00%
other: 17/34 = 50.00%

In [ ]:
for r in baseline_results_100:
    qtype = get_question_type(r["question"])

    if qtype == "other":
        print("=" * 80)
        print(r["question"])

================================================================================
True or false: event (Oliver Jensen was married to Chris Evans) and event (Oliver Jensen was born in Bristol, Connecticut) started at the same year?
================================================================================
True or false: event (Oliver Jensen was married to Chris Evans) and event (Chris Evans owned Pearl Network) started at the same year?
================================================================================
True or false: event (Chris Evans was married to Oliver Jensen) and event (Chris Evans owned Pearl Network) started at the same year?
================================================================================
True or false: event (Oliver Jensen was married to Chris Evans) was still happening when event (Chris Evans won prize Victory Achievement Award) started?
================================================================================
True or false: event (Oliver Jensen was married to Chris Evans) was still happening when event (Chris Evans owned Pearl Network) started?
================================================================================
What happened right after the event (Chris Evans owned Pearl Network) starts?
================================================================================
What happened right after the event (Oliver Jensen was born in Bristol, Connecticut) starts?
================================================================================
What happened right before the event (Chris Evans owned Pearl Network) ends?
================================================================================
What happened right before the event (Chris Evans won prize Victory Achievement Award) starts?
================================================================================
What happened right after the event (Chris Evans was married to Oliver Jensen) starts?
================================================================================
True or false: event (Chris Evans owned Pearl Network) was longer in duration than event (Oliver Jensen was married to Chris Evans)?
================================================================================
True or false: event (Chris Evans owned Pearl Network) was longer in duration than event (Chris Evans was married to Oliver Jensen)?
================================================================================
True or false: event (Chris Evans was married to Oliver Jensen) was longer in duration than event (Oliver Jensen was married to Chris Evans)?
================================================================================
True or false: event (Paul Anderson played for Greenfield United (Chicago)) and event (Paul Anderson played for Blazing Tigers (Hartford)) started at the same year?
================================================================================
True or false: event (Paul Anderson was born in Austin) and event (Paul Anderson played for Northern Rovers F.C.) started at the same year?
================================================================================
True or false: event (Paul Anderson played for Blazing Tigers (Hartford)) and event (Paul Anderson played for Denver national under-20 basketball team) started at the same year?
================================================================================
True or false: event (Paul Anderson played for Blazing Tigers (Hartford)) was still happening when event (Paul Anderson played for Ocean City Football Club) started?
================================================================================
True or false: event (Paul Anderson played for Blazing Tigers (Hartford)) was still happening when event (Paul Anderson played for London Sporting Club) started?
================================================================================
True or false: event (Paul Anderson played for London Sporting Club) was still happening when event (Paul Anderson played for Greenfield United (Chicago)) started?
================================================================================
What happened right after the event (Paul Anderson played for Ocean City Football Club) starts?
================================================================================
What happened right after the event (Paul Anderson played for Oliverstown United) starts?
================================================================================
What happened right before the event (Paul Anderson played for Northern Rovers F.C.) ends?
================================================================================
What happened right before the event (Paul Anderson played for Greenfield United (Chicago)) ends?
================================================================================
What happened right before the event (Paul Anderson played for Greenfield United (Chicago)) starts?
================================================================================
True or false: event (Paul Anderson played for Ocean City Football Club) was longer in duration than event (Paul Anderson played for Denver national under-20 basketball team)?
================================================================================
True or false: event (Paul Anderson played for London Sporting Club) was longer in duration than event (Paul Anderson played for Denver national under-20 basketball team)?
================================================================================
True or false: event (Paul Anderson played for Greenfield United (Chicago)) was longer in duration than event (Paul Anderson played for Blazing Tigers (Hartford))?
================================================================================
True or false: event (Harry Johnson (footballer) played for Skye United F.C.) and event (Harry Johnson (footballer) was born in Austin) started at the same year?
================================================================================
True or false: event (Harry Johnson (footballer) played for Rapid City Raiders) and event (Harry Johnson (footballer) played for London national football B team) started at the same year?
================================================================================
True or false: event (Harry Johnson (footballer) was born in Austin) and event (Harry Johnson (footballer) played for Greenland national under-21 football team) started at the same year?
================================================================================
True or false: event (Harry Johnson (footballer) played for Redwood City FC) was still happening when event (Harry Johnson (footballer) played for London national football B team) started?
================================================================================
True or false: event (Harry Johnson (footballer) played for Redwood City FC) was still happening when event (Harry Johnson (footballer) played for Rapid City Raiders) started?
================================================================================
True or false: event (Harry Johnson (footballer) played for Redwood City FC) was still happening when event (Harry Johnson (footballer) played for Silver Lake Galaxy) started?
================================================================================
What happened right before the event (Harry Johnson (footballer) played for Redwood City FC) starts?

In [ ]:
no_answer_cases = [
    r for r in baseline_results_100
    if r["prediction"] == "NO_ANSWER_FOUND"
]

print("NO_ANSWER_FOUND cases:", len(no_answer_cases))

for r in no_answer_cases[:5]:
    print("=" * 80)
    print("INDEX:", r["index"])
    print("QUESTION:")
    print(r["question"])
    print("\nGROUND TRUTH:")
    print(r["ground_truth"])
    print("\nFULL RESPONSE:")
    print(r["full_response"][:2000])

NO_ANSWER_FOUND cases: 0

In [ ]:
wrong_cases = []

for r in baseline_results_100:
    pred = normalize_text(r["prediction"])
    gt = normalize_text(r["ground_truth"])

    if pred != gt:
        wrong_cases.append(r)

print("Wrong cases:", len(wrong_cases))

for r in wrong_cases[:10]:
    print("=" * 80)
    print("INDEX:", r["index"])
    print("QUESTION:")
    print(r["question"])
    print("\nGROUND TRUTH:")
    print(r["ground_truth"])
    print("\nPREDICTION:")
    print(r["prediction"])

Wrong cases: 51
================================================================================
INDEX: 4
QUESTION:
Given the following five events: (Chris Evans won prize Victory Achievement Award), (Chris Evans owned Pearl Network), (Chris Evans was born in Bristol, Connecticut), (Chris Evans was married to Oliver Jensen), (Oliver Jensen was born in Bristol, Connecticut). Which event is the second one in chronological order?

GROUND TRUTH:
Chris Evans was born in Bristol, Connecticut

PREDICTION:
Chris Evans owned Pearl Network
================================================================================
INDEX: 6
QUESTION:
Given the following five events: (Chris Evans won prize Victory Achievement Award), (Chris Evans owned Pearl Network), (Chris Evans was born in Bristol, Connecticut), (Chris Evans was married to Oliver Jensen), (Oliver Jensen was born in Bristol, Connecticut). Which event is the fourth one in chronological order?

GROUND TRUTH:
Chris Evans owned Pearl Network

PREDICTION:
Oliver Jensen was married to Chris Evans
================================================================================
INDEX: 7
QUESTION:
Given the following five events: (Chris Evans won prize Victory Achievement Award), (Chris Evans owned Pearl Network), (Chris Evans was born in Bristol, Connecticut), (Chris Evans was married to Oliver Jensen), (Oliver Jensen was born in Bristol, Connecticut). Which event is the fifth one in chronological order?

GROUND TRUTH:
Chris Evans won prize Victory Achievement Award

PREDICTION:
Chris Evans was married to Oliver Jensen
================================================================================
INDEX: 9
QUESTION:
Given the following five events: (Oliver Jensen was born in Bristol, Connecticut), (Chris Evans won prize Victory Achievement Award), (Chris Evans owned Pearl Network), (Oliver Jensen was married to Chris Evans), (Chris Evans was married to Oliver Jensen). Which event is the second one in chronological order?

GROUND TRUTH:
Oliver Jensen was married to Chris Evans

PREDICTION:
Chris Evans won prize Victory Achievement Award
================================================================================
INDEX: 10
QUESTION:
Given the following five events: (Oliver Jensen was born in Bristol, Connecticut), (Chris Evans won prize Victory Achievement Award), (Chris Evans owned Pearl Network), (Oliver Jensen was married to Chris Evans), (Chris Evans was married to Oliver Jensen). Which event is the third one in chronological order?

GROUND TRUTH:
Oliver Jensen was married to Chris Evans

PREDICTION:
Chris Evans owned Pearl Network
================================================================================
INDEX: 11
QUESTION:
Given the following five events: (Oliver Jensen was born in Bristol, Connecticut), (Chris Evans won prize Victory Achievement Award), (Chris Evans owned Pearl Network), (Oliver Jensen was married to Chris Evans), (Chris Evans was married to Oliver Jensen). Which event is the fourth one in chronological order?

GROUND TRUTH:
Chris Evans owned Pearl Network

PREDICTION:
Chris Evans won prize Victory Achievement Award
================================================================================
INDEX: 13
QUESTION:
How long did the event (Chris Evans owned Pearl Network) last?

GROUND TRUTH:
8 years

PREDICTION:
7 years
================================================================================
INDEX: 14
QUESTION:
How long did the event (Oliver Jensen was married to Chris Evans) last?

GROUND TRUTH:
40 years

PREDICTION:
40
================================================================================
INDEX: 15
QUESTION:
How long did the event (Chris Evans was married to Oliver Jensen) last?

GROUND TRUTH:
40 years

PREDICTION:
10 years
================================================================================
INDEX: 16
QUESTION:
How much time passed between the start of event (Oliver Jensen was born in Bristol, Connecticut) and the start of event (Oliver Jensen was married to Chris Evans)?

GROUND TRUTH:
22 years

PREDICTION:
0

In [ ]:
import re

def normalize_for_eval(text):
    text = normalize_text(text)

    # Convert "40 years" -> "40"
    # Convert "1 year" -> "1"
    match = re.fullmatch(r"(\d+)\s*years?", text)
    if match:
        return match.group(1)

    return text

In [ ]:
correct = 0

for r in baseline_results_100:
    pred = normalize_for_eval(r["prediction"])
    gt = normalize_for_eval(r["ground_truth"])

    if pred == gt:
        correct += 1

print("Correct:", correct)
print("Incorrect:", len(baseline_results_100) - correct)
print("Accuracy:", correct / len(baseline_results_100))

Correct: 59
Incorrect: 41
Accuracy: 0.59

# Experiment B: Qwen Baseline with Repo-Style Inference

In [ ]:
EXPERIMENT_NAME = "qwen_baseline_100_repo_style"
RESULTS_FILE = f"{results_dir}/{EXPERIMENT_NAME}.json"

qwen_repo_style_100 = load_json(RESULTS_FILE)

print("Experiment:", EXPERIMENT_NAME)
print("Already processed:", len(qwen_repo_style_100))

Loaded existing file: /content/drive/MyDrive/TISER_Project/results/qwen_baseline_100_repo_style.json
Existing records: 100
Experiment: qwen_baseline_100_repo_style
Already processed: 100

In [ ]:
start_idx = len(qwen_repo_style_100)

for idx in range(start_idx, 100):

    sample = test_examples[idx]
    prompt = sample["prompt"]

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=512,
        do_sample=False,
        repetition_penalty=1.1
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    response = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    prediction = extract_answer(response)

    qwen_repo_style_100.append({
        "index": idx,
        "question": sample["question"],
        "ground_truth": sample["answer"],
        "prediction": prediction,
        "full_response": response
    })

    save_json(qwen_repo_style_100, RESULTS_FILE)

    print(f"Processed and saved {idx+1}/100")

print("\nRepo-style baseline evaluation complete")
print("Total results:", len(qwen_repo_style_100))

Repo-style baseline evaluation complete
Total results: 100

In [ ]:
correct = 0

for r in qwen_repo_style_100:
    pred = normalize_for_eval(r["prediction"])
    gt = normalize_for_eval(r["ground_truth"])

    if pred == gt:
        correct += 1

print("Correct:", correct)
print("Incorrect:", len(qwen_repo_style_100) - correct)
print("Accuracy:", correct / len(qwen_repo_style_100))

Correct: 59
Incorrect: 41
Accuracy: 0.59

In [ ]:
import re
from collections import Counter

def tokenize_for_f1(text):
    text = normalize_text(text)
    return re.findall(r"\w+", text)

def f1_score(prediction, ground_truth):
    pred_tokens = tokenize_for_f1(prediction)
    gt_tokens = tokenize_for_f1(ground_truth)

    if len(pred_tokens) == 0 and len(gt_tokens) == 0:
        return 1.0

    if len(pred_tokens) == 0 or len(gt_tokens) == 0:
        return 0.0

    common = Counter(pred_tokens) & Counter(gt_tokens)
    num_same = sum(common.values())

    if num_same == 0:
        return 0.0

    precision = num_same / len(pred_tokens)
    recall = num_same / len(gt_tokens)

    return 2 * precision * recall / (precision + recall)

In [ ]:
f1_scores = []

for r in qwen_repo_style_100:
    f1_scores.append(
        f1_score(
            r["prediction"],
            r["ground_truth"]
        )
    )

print("Average F1:", sum(f1_scores) / len(f1_scores))

Average F1: 0.7431600948071536

In [ ]:
import re
from collections import Counter

def repo_normalize(text):
    text = str(text).lower()

    # remove common tags
    text = re.sub(r"</?answer>", " ", text)
    text = re.sub(r"</?reasoning>", " ", text)
    text = re.sub(r"</?timeline>", " ", text)
    text = re.sub(r"</?reflection>", " ", text)

    # punctuation -> spaces
    text = re.sub(r"[^a-z0-9]+", " ", text)

    # collapse spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


def repo_f1(prediction, ground_truth):
    pred = repo_normalize(prediction)
    gt = repo_normalize(ground_truth)

    pred_tokens = pred.split()
    gt_tokens = gt.split()

    if len(pred_tokens) == 0 and len(gt_tokens) == 0:
        return 1.0

    if len(pred_tokens) == 0 or len(gt_tokens) == 0:
        return 0.0

    common = Counter(pred_tokens) & Counter(gt_tokens)
    overlap = sum(common.values())

    if overlap == 0:
        return 0.0

    precision = overlap / len(pred_tokens)
    recall = overlap / len(gt_tokens)

    return 2 * precision * recall / (precision + recall)


f1_scores = []

for r in qwen_repo_style_100:
    f1_scores.append(
        repo_f1(
            r["prediction"],
            r["ground_truth"]
        )
    )

print("Repo-style F1:", sum(f1_scores) / len(f1_scores))

Repo-style F1: 0.7431600948071536

In [ ]:
!git clone https://github.com/arianmo477/MultilingualTemporalReasoningTISER.git

Cloning into 'MultilingualTemporalReasoningTISER'...
remote: Enumerating objects: 348, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 348 (delta 40), reused 63 (delta 36), pack-reused 263 (from 3)
Receiving objects: 100% (348/348), 110.01 MiB | 16.02 MiB/s, done.
Resolving deltas: 100% (92/92), done.
Updating files: 100% (96/96), done.
Filtering content: 100% (47/47), 1.94 GiB | 33.26 MiB/s, done.

In [ ]:
%cd MultilingualTemporalReasoningTISER

!find . -maxdepth 3 -type f

/content/MultilingualTemporalReasoningTISER
./LICENSE
./environment.yml
./CODE_OF_CONDUCT.md
./data/prompts/tiser_full_de.txt
./data/prompts/tiser_full_fr.txt
./data/prompts/tiser_full_it.txt
./data/prompts/tiser_full_en.txt
./data/.gitattributes
./data/invalid_samples_train.json
./data/TISER_test.json
./data/invalid_samples_test.json
./data/TISER_train.json
./CONTRIBUTING.md
./multilingual_rag_tiser/rag/retriever.py
./multilingual_rag_tiser/rag/__init__.py
./multilingual_rag_tiser/rag/rag_prompt.py
./multilingual_rag_tiser/rag/build_rag_index.py
./multilingual_rag_tiser/evaluation/inference.py
./multilingual_rag_tiser/evaluation/run_eval_rag.sh
./multilingual_rag_tiser/preprocess/validate_tiser_dataset.py
./multilingual_rag_tiser/preprocess/run_validate_dataset.sh
./multilingual_rag_tiser/preprocess/run_mix_dataset.sh
./multilingual_rag_tiser/preprocess/mix_dataset.py
./multilingual_rag_tiser/training/run_train.sh
./multilingual_rag_tiser/training/train_qlora.py
./multilingual_rag_tiser/translate/run_score.sh
./multilingual_rag_tiser/translate/translate_dataset.py
./multilingual_rag_tiser/translate/score_translation.py
./multilingual_rag_tiser/translate/run_translate.sh
./.git/config
./.git/index
./.git/HEAD
./.git/info/exclude
./.git/packed-refs
./.git/logs/HEAD
./.git/hooks/push-to-checkout.sample
./.git/hooks/update.sample
./.git/hooks/post-commit
./.git/hooks/post-update.sample
./.git/hooks/pre-commit.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/pre-push.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/pre-receive.sample
./.git/hooks/commit-msg.sample
./.git/hooks/post-checkout
./.git/hooks/post-merge
./.git/hooks/pre-push
./.git/description
./utils/utils.py
./utils/translation_quality.py
./utils/metrics.py
./utils/__pycache__/prompt.cpython-310.pyc
./utils/__pycache__/text_processing.cpython-310.pyc
./utils/__pycache__/translation_utils.cpython-310.pyc
./utils/__pycache__/translation_quality.cpython-310.pyc
./utils/__pycache__/evaluation.cpython-310.pyc
./utils/__pycache__/metrics.cpython-310.pyc
./utils/__pycache__/rag_utils.cpython-310.pyc
./utils/__pycache__/utils.cpython-310.pyc
./utils/__pycache__/__init__.cpython-310.pyc
./utils/__pycache__/io_gpu.cpython-310.pyc
./utils/rag_utils.py
./utils/__init__.py
./utils/prompt.py
./utils/io_gpu.py
./utils/translation_utils.py
./README.md

In [ ]:
!sed -n '1,220p' README.md

# tiser-multilingual

Multilingual temporal reasoning with a small language model — a two-part extension of [TISER](https://aclanthology.org/2025.acl-long.1358/) (Bazaga et al., ACL 2025):

1. **Small-model adaptation** — Qwen2.5-3B-Instruct + QLoRA on a single 8 GB GPU, matching the spirit of the original paper's reasoning pipeline without requiring 40+ GB of VRAM.

2. **Multilingual extension** — an NLLB-based translation pipeline that produces structurally faithful Italian, German, French, and Persian training data, enabling a single fine-tuned model to reason temporally across languages.

The original TISER paper uses Qwen2.5-7B and Mistral-7B on English only. This project reaches strong English-only performance with a 3 B model and extends the same temporal-reasoning pipeline to multilingual EN · IT · DE · FR training.

---

## Results

Most evaluations use approximately **500 samples** across the five TISER categories: `tgqa`, `tempreason_l2`, `tempreason_l3`, `timeqa_easy`, and `timeqa_hard`. Some runs are exactly balanced with 100 samples per category, while others use a near-balanced split depending on the available filtered samples.

### English-only model — EN (15 000 training samples)

Evaluated on 500 English samples balanced across the five TISER categories:

| | F1 | chrF | NormEM | EM | SoftEM | EngLeak |
|---|---:|---:|---:|---:|---:|---:|
| **Overall** | 0.921 | 90.18 | 0.844 | 0.838 | 0.912 | 0.000 |

Per dataset:

| Dataset | F1 | chrF | NormEM | EM | SoftEM | N |
|---|---:|---:|---:|---:|---:|---:|
| timeqa_easy | 0.974 | 97.98 | 0.960 | 0.960 | 0.980 | 100 |
| timeqa_hard | 0.981 | 98.39 | 0.950 | 0.950 | 0.960 | 100 |
| tempreason_l3 | 0.956 | 96.03 | 0.950 | 0.950 | 0.950 | 100 |
| tempreason_l2 | 0.840 | 85.05 | 0.810 | 0.810 | 0.810 | 100 |
| tgqa | 0.854 | 73.46 | 0.550 | 0.520 | 0.860 | 100 |

### Italian-only model — IT, 15k training samples

Evaluated on 500 Italian samples across the five TISER categories.

**Overall**

| F1 | chrF | NormEM | EM | SoftEM | EngLeak |
|---:|---:|---:|---:|---:|---:|
| 0.881 | 87.67 | 0.790 | 0.772 | 0.838 | 0.006 |

**Per dataset**

| Dataset | F1 | chrF | NormEM | EM | SoftEM | EngLeak | N |
|---|---:|---:|---:|---:|---:|---:|---:|
| timeqa_easy | 0.974 | 97.46 | 0.955 | 0.955 | 0.966 | 0.000 | 88 |
| timeqa_hard | 0.923 | 94.48 | 0.885 | 0.885 | 0.885 | 0.000 | 96 |
| tempreason_l3 | 0.892 | 90.14 | 0.860 | 0.822 | 0.879 | 0.028 | 107 |
| tempreason_l2 | 0.807 | 80.34 | 0.733 | 0.695 | 0.733 | 0.000 | 105 |
| tgqa | 0.828 | 77.96 | 0.548 | 0.539 | 0.750 | 0.000 | 104 |

### Two-language model — EN + IT (15 000 training samples)

Evaluated on 500 samples: 250 English and 250 Italian.

| | F1 | chrF | NormEM | EM | SoftEM | EngLeak |
|---|---:|---:|---:|---:|---:|---:|
| **Overall** | 0.892 | 88.07 | 0.802 | 0.794 | 0.860 | 0.010 |
| English | 0.911 | 89.34 | 0.836 | 0.832 | 0.900 | 0.000 |
| Italian | 0.873 | 86.80 | 0.768 | 0.756 | 0.820 | 0.020 |

Per dataset:

| Dataset | F1 | EM | N |
|---|---:|---:|---:|
| timeqa_easy | 0.957 | 0.930 | 100 |
| timeqa_hard | 0.925 | 0.860 | 100 |
| tempreason_l3 | 0.930 | 0.880 | 100 |
| tempreason_l2 | 0.817 | 0.760 | 100 |
| tgqa | 0.831 | 0.540 | 100 |

### Four-language model — EN + IT + DE + FR (15 000 training samples)

Evaluated on 500 samples: 125 per language.

| | F1 | chrF | NormEM | EM | SoftEM | EngLeak |
|---|---:|---:|---:|---:|---:|---:|
| **Overall** | 0.888 | 88.14 | 0.798 | 0.792 | 0.856 | 0.006 |
| English | 0.925 | 91.75 | 0.840 | 0.840 | 0.912 | 0.000 |
| German | 0.905 | 88.40 | 0.816 | 0.816 | 0.888 | 0.008 |
| Italian | 0.887 | 89.48 | 0.800 | 0.784 | 0.856 | 0.008 |
| French | 0.834 | 82.94 | 0.736 | 0.728 | 0.768 | 0.008 |

Per dataset:

| Dataset | F1 | EM | N |
|---|---:|---:|---:|
| timeqa_easy | 0.980 | 0.950 | 100 |
| timeqa_hard | 0.928 | 0.880 | 100 |
| tempreason_l3 | 0.899 | 0.860 | 100 |
| tempreason_l2 | 0.838 | 0.770 | 100 |
| tgqa | 0.793 | 0.500 | 100 |

**Notes.**

The English-only model gives the strongest overall result, which is expected because it is trained and evaluated only on the original English distribution. The multilingual models trade a small amount of English performance for cross-lingual temporal reasoning ability.

French scores slightly lower than the other languages due to translation quality issues in the NLLB pipeline, especially carrier-prefix artifacts and isolated-entity translation noise. EngLeak remains very low across multilingual models, meaning the fine-tuned model almost never regresses to English when answering in a non-English language. `tgqa` is the hardest category because answers require matching free-form event descriptions rather than mostly entity names or numeric values.

---

## What this adds over the original TISER paper

| | TISER original | tiser-multilingual |
|---|---|---|
| Model | 7 B Qwen2.5 / Mistral | **3 B** Qwen2.5-Instruct |
| VRAM | ~40 GB | **8 GB** QLoRA 4-bit NF4 |
| Languages | English only | EN · IT · DE · FR |
| Training data | English only | English + NLLB-translated multilingual data |
| Metrics | EM, F1 | EM, NormEM, SoftEM, F1, chrF, EngLeak |

---

## Installation

```bash
git clone https://github.com/<your-username>/tiser-multilingual.git
cd tiser-multilingual

conda create -n tiser python=3.10
conda activate tiser

pip install torch --index-url https://download.pytorch.org/whl/cu118
pip install transformers peft bitsandbytes datasets tqdm
pip install "transformers[sentencepiece]" sentence-transformers sacremoses

export PYTHONPATH="$(pwd):${PYTHONPATH:-}"
```


### Project structure
```bash
tiser-multilingual/
│
├── tiser_lite/
│   ├── training/
│   │   ├── train_qlora.py          # QLoRA fine-tuning
│   │   └── run_train.sh            # Training launcher
│   │
│   ├── evaluation/
│   │   ├── inference.py            # Inference + metric computation
│   │   └── run_eval.sh             # Multi-language eval launcher
│   │
│   ├── translate/
│   │   └── translate_dataset.py    # NLLB translation pipeline
│   │
│   └── preprocess/
│       ├── mix_dataset.py          # Balanced multilingual mixer
│       └── run_mix_dataset.sh      # Mixer launcher
│
├── utils/
│   ├── metrics.py                  # EM, NormEM, SoftEM, F1, chrF, EngLeak
│   ├── prompt.py                   # Prompt builder shared by train + eval
│   ├── translation_utils.py        # Language packs, hallucination filter
│   └── io_gpu.py                   # JSON I/O, balanced sampling
│
├── data/
│   ├── prompts/
│   │   ├── tiser_full_en.txt          # English prompt
│   │   ├── tiser_full_it.txt       # Italian prompt
│   │   ├── tiser_full_de.txt       # German prompt
│   │   └── tiser_full_fr.txt       # French prompt
│   └── splits/
│       ├── train/                  # Per-language + mixed training JSONs
│       └── test/                   # Per-language test JSONs
│
└── experiments/                    # Checkpoints and result JSONs
```


### Training
 English-only model
```bash
bash multilingual_tiser/training/run_train.sh qwen en tiser_full 15000
```

 Two-language model: EN + IT
```bash
#Build the mixed training file
bash multilingual_tiser/preprocess/run_mix_dataset.sh train en,it 15000
# Fine-tune
bash multilingual_tiser/training/run_train.sh qwen en_it_mixed tiser_full 15000
```
# Key training hyperparameters

| Hyperparameter        | Value                          |
| --------------------- | ------------------------------ |
| Base model            | `Qwen/Qwen2.5-3B-Instruct`     |
| Quantization          | NF4 4-bit, double quantization |
| LoRA rank / alpha     | 16 / 32                        |
| LoRA dropout          | 0.05                           |
| Max sequence length   | 1 536 tokens                   |
| Per-device batch size | 1                              |
| Gradient accumulation | 16                             |
| Optimizer             | `paged_adamw_8bit`             |
| Learning rate         | 3 × 10⁻⁴                       |
| Epochs                | 2                              |
| Validation split      | 10 %                           |



### Evaluation
Single language
```bash
bash tiser_lite/evaluation/run_eval.sh qwen en \
    experiments/qwen/en_15000_8gb_val_qlora/ \
    iterative tiser_full 500
```
Two-language model
```bash
bash tiser_lite/evaluation/run_eval.sh qwen en,it \
    experiments/qwen/en_it_mixed_tiser_full_15000_8gb_val_qlora/ \
    iterative tiser_full 500
```
Four-language model
```bash
bash tiser_lite/evaluation/run_eval.sh qwen en,it,de,fr \

In [ ]:
from collections import Counter

dataset_counts = Counter(
    sample["dataset_name"]
    for sample in test_examples
)

print(dataset_counts)

Counter({'tempreason_l2_test': 5397, 'tempreason_l3_test': 4426, 'tgqa_test': 3316, 'timeqa_hard_test': 3078, 'timeqa_easy_test': 2997, 'tot_semantic_test': 2800})

In [ ]:
target_datasets = [
    "tgqa_test",
    "tempreason_l2_test",
    "tempreason_l3_test",
    "timeqa_easy_test",
    "timeqa_hard_test"
]

balanced_500 = []

for dataset_name in target_datasets:
    selected = [
        sample for sample in test_examples
        if sample["dataset_name"] == dataset_name
    ][:100]

    print(dataset_name, len(selected))
    balanced_500.extend(selected)

print("Total balanced samples:", len(balanced_500))

tgqa_test 100
tempreason_l2_test 100
tempreason_l3_test 100
timeqa_easy_test 100
timeqa_hard_test 100
Total balanced samples: 500

In [ ]:
EXPERIMENT_NAME = "qwen_baseline_500_balanced_repo_style"
RESULTS_FILE = f"{results_dir}/{EXPERIMENT_NAME}.json"

qwen_baseline_500 = load_json(RESULTS_FILE)

print("Experiment:", EXPERIMENT_NAME)
print("Already processed:", len(qwen_baseline_500))

Loaded existing file: /content/drive/MyDrive/TISER_Project/results/qwen_baseline_500_balanced_repo_style.json
Existing records: 500
Experiment: qwen_baseline_500_balanced_repo_style
Already processed: 500

In [ ]:
start_idx = len(qwen_baseline_500)

for idx in range(start_idx, 500):

    sample = balanced_500[idx]
    prompt = sample["prompt"]

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=512,
        do_sample=False,
        repetition_penalty=1.1
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    response = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    prediction = extract_answer(response)

    qwen_baseline_500.append({
        "index": idx,
        "dataset_name": sample["dataset_name"],
        "question": sample["question"],
        "ground_truth": sample["answer"],
        "prediction": prediction,
        "full_response": response
    })

    save_json(qwen_baseline_500, RESULTS_FILE)

    print(f"Processed and saved {idx+1}/500")

print("\nBalanced 500 baseline evaluation complete")
print("Total results:", len(qwen_baseline_500))

Balanced 500 baseline evaluation complete
Total results: 500

In [ ]:
correct = 0

for r in qwen_baseline_500:
    pred = normalize_for_eval(r["prediction"])
    gt = normalize_for_eval(r["ground_truth"])

    if pred == gt:
        correct += 1

print("NormEM Correct:", correct)
print("Total:", len(qwen_baseline_500))
print("NormEM:", correct / len(qwen_baseline_500))

NormEM Correct: 305
Total: 500
NormEM: 0.61

In [ ]:
f1_scores = []

for r in qwen_baseline_500:
    f1_scores.append(
        repo_f1(
            r["prediction"],
            r["ground_truth"]
        )
    )

print("F1:", sum(f1_scores) / len(f1_scores))

F1: 0.7033636262430379

In [ ]:
# Show repo prompt
with open("data/prompts/tiser_full_en.txt", "r", encoding="utf-8") as f:
    repo_prompt = f.read()

print("Repo prompt first 1000 chars:")
print(repo_prompt[:1000])

print("\n" + "="*80 + "\n")

# Show one dataset prompt
sample_prompt = balanced_500[0]["prompt"]

print("Dataset prompt first 1000 chars:")
print(sample_prompt[:1000])

Repo prompt first 1000 chars:
You are an AI assistant that uses a Chain of Thought (CoT) approach with reflection to answer queries. Follow the steps below:

Step 1: Reason through the problem step by step within the <reasoning> section.

Step 2: Based on your reasoning, identify the relevant temporal events needed to answer the given question within the <timeline> section. Assume that temporal relations in the context are unidirectional.

Step 3: Review your reasoning and the constructed timeline to check for any errors or possible improvements within the <reflection> section.

Step 4: If necessary, revise your reasoning based on your reflection. If additional reasoning is required, return to Step 1; otherwise, proceed to the next step.

Step 5: Provide the final, concise answer only within the <answer> section. If the answer is a number, output only the number and nothing else. Otherwise, output only the entity or event name without any additional explanation.

Additional instructions:
• If this is during data ge

================================================================================

Dataset prompt first 1000 chars:
### Question:

    You are an AI assistant that uses a Chain of Thought (CoT) approach with reflection to answer queries. Follow these steps:

Step 1. Reason through the problem step by step within the <reasoning> tags.
Step 2. Given your previous reasoning, identify relevant temporal events in the given context for answering the given question within <timeline> tags. Assume relations in the context are unidirectional.
Step 3. Reflect on your reasoning and the timeline to check for any errors or improvements within the <reflection> tags.
Step 4. Make any necessary adjustments based on your reflection. If there is additional reasoning required, go back to Step 1 (reason through the problem step-by-step), otherwise move to the next step (Step 5).
Step 5. Provide your final, concise answer within the <answer> tags. If the answer is a number, just output the number nothing else. Otherwise output the entity or event, without any additional comments.

Important: The <reasoning>, <reflect

In [ ]:
print("Repo prompt length:", len(repo_prompt))
print("Dataset prompt length:", len(sample_prompt))

print("Repo prompt in dataset prompt?", repo_prompt.strip()[:200] in sample_prompt)

Repo prompt length: 1577
Dataset prompt length: 2525
Repo prompt in dataset prompt? False

In [ ]:
sample = balanced_500[0]

print(sample.keys())
print(sample["question"])
print(sample["answer"])
print(sample["prompt"][-1500:])

dict_keys(['dataset_name', 'question_id', 'question', 'prompt', 'answer'])
Which event started first, (Chris Evans was married to Oliver Jensen) or (Chris Evans was born in Bristol, Connecticut)?
Chris Evans was born in Bristol, Connecticut
ons are for your internal reasoning process. All the reflection and the timeline have to be contained inside the thinking section.
Do not use enumerations or lists when writing, use plain text instead such as paragraphs.
The response to the query must be entirely contained within the <answer> tags.

Use the following format for your response:

    <reasoning>
[Your step-by-step reasoning goes here. This is your internal thought process.]
<timeline>
[Relevant temporal events for answering the given question.]
</timeline>
<reflection>
[Your reflection on your reasoning, checking for errors, improvements or changes required]
</reflection>
[Any adjustments to your thinking based on your reflection]
</reasoning>
<answer>
[Your final, concise answer to the query.]
</answer>

    Question: Which event started first, (Chris Evans was married to Oliver Jensen) or (Chris Evans was born in Bristol, Connecticut)?

    Temporal context: (Chris Evans was born in Bristol, Connecticut) starts at 1948. (Oliver Jensen was born in Bristol, Connecticut) starts at 1948. (Chris Evans was married to Oliver Jensen) starts at 1970. (Oliver Jensen was married to Chris Evans) starts at 1970. (Chris Evans owned Pearl Network) starts at 2005. (Chris Evans won prize Victory Achievement Award) starts at 2007. (Chris Evans was married to Oliver Jensen) ends at 2010. (Oliver Jensen was married to Chris Evans) ends at 2010. (Chris Evans owned Pearl Network) ends at 2013

    ### Answer:

In [ ]:
!sed -n '1,250p' utils/prompt.py

"""
utils/prompt.py
Prompt construction shared by training and inference.
"""


def build_prompt(ex: dict, prompt: str) -> str:
    """
    Build the prompt for training or inference.

    Both share the same base format:
        {instr}\n\nContext:\n{ctx}\n\nQuestion:\n{qst}\n\n


    Args:
        ex:            dataset example with keys:
                         prompt, temporal_context (or context), question
        for_inference: True for eval/inference, False for training

    Returns:
        Prompt string, ending with "<reasoning>" iff for_inference=True.
    """

    instr = prompt.strip()
    ctx   = (ex.get("temporal_context", "") or ex.get("context", "") or "").strip()
    qst   = (ex.get("question", "") or "").strip()

    base = (
        f"{instr}\n\n"
        f"Context:\n{ctx}\n\n"
        f"Question:\n{qst}\n\n"
    )


    return base

In [ ]:
!sed -n '1,250p' utils/io_gpu.py

import gc
import hashlib
import json
import logging
import os
import random
from collections import Counter, defaultdict
from pathlib import Path

from functools import lru_cache
from pathlib import Path
import torch

log = logging.getLogger(__name__)

# ==================================================
# GPU / MEMORY
# ==================================================

def verify_gpu():
    print("===== GPU CHECK =====")
    print("CUDA available:", torch.cuda.is_available())
    if not torch.cuda.is_available():
        print("WARNING: CUDA is not available. Training will fail unless on CPU mode.")
    else:
        print("GPU:", torch.cuda.get_device_name(0))
        props = torch.cuda.get_device_properties(0)
        print("VRAM (GB):", round(props.total_memory / (1024**3), 2))
    print("=====================")


def clean_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


# ==================================================
# IO
# ==================================================

def load_json(path):
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(path)

    if path.stat().st_size == 0:
        return None

    with open(path, "r", encoding="utf-8") as f:
        first = f.read(1)
        f.seek(0)

        # Normal JSON list or dict
        if first in ["[", "{"]:
            return json.load(f)

        # JSONL fallback
        return [json.loads(line) for line in f if line.strip()]

def _strip_invalid_unicode(obj):
    """Recursively removes invalid unicode surrogates from strings."""
    if isinstance(obj, str):
        return obj.encode("utf-8", "ignore").decode("utf-8")
    elif isinstance(obj, list):
        return [_strip_invalid_unicode(x) for x in obj]
    elif isinstance(obj, dict):
        return {k: _strip_invalid_unicode(v) for k, v in obj.items()}
    return obj

def save_json(path, data):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    clean_data = _strip_invalid_unicode(data)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(clean_data, f, indent=2, ensure_ascii=False)

def save_json_atomic(obj, path):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    tmp = p.with_suffix(p.suffix + ".tmp")
    clean_obj = _strip_invalid_unicode(obj)

    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(clean_obj, f, ensure_ascii=False, indent=2)

    tmp.replace(p)


def load_txt_as_string(path: str, fallback: str = "") -> str:
    if not os.path.exists(path):
        log.warning("Prompt file not found at %s. Using fallback.", path)
        return fallback
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read().strip()
        return content if content else fallback
    except Exception as e:
        log.error("Error reading prompt file: %s. Using fallback.", e)
        return fallback



def balance_by_dataset_name(data, category, max_samples, seed=42):
    random.seed(seed)
    buckets = defaultdict(list)
    for x in data:
        if category == "test" and x["dataset_name"] == "tot_semantic_test":
            continue
        buckets[x["dataset_name"]].append(x)

    names = list(buckets.keys())
    base = max_samples // len(names)
    selected = []
    leftovers = []

    for name in names:
        if len(buckets[name]) <= base:
            selected.extend(buckets[name])
            leftovers += buckets[name][:]
        else:
            sel = random.sample(buckets[name], base)
            selected.extend(sel)
            leftovers += [x for x in buckets[name] if x not in sel]

    remaining = max_samples - len(selected)
    if remaining > 0 and leftovers:
        selected.extend(random.sample(leftovers, min(remaining, len(leftovers))))

    random.shuffle(selected)
    return selected




@lru_cache(maxsize=16)
def load_prompt_for_lang(prompt_name, lang):
    """Per-language prompt template, falling back to base English if the
    language-specific file is missing. Cached so we don't reread on every
    sample."""
    specific = Path(f"data/prompts/{prompt_name}_{lang}.txt")
    fallback = Path(f"data/prompts/{prompt_name}.txt")
    path = specific if specific.exists() else fallback
    if not path.exists():
        raise FileNotFoundError(
            f"Prompt template not found: tried {specific} and {fallback}"
        )
    return load_txt_as_string(str(path)).strip()


# ==================================================
# STATS / HASHING  (moved from utils.py)
# ==================================================

def save_stats(stats_path: str | Path, stats_dict: dict) -> None:
    p = Path(stats_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(stats_dict, f, ensure_ascii=False, indent=2)


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def language_counts(data: list[dict]) -> dict[str, int]:
    return dict(Counter(s.get("language", "unknown") for s in data))

In [ ]:
!sed -n '1,300p' multilingual_rag_tiser/evaluation/inference.py

#!/usr/bin/env python3
"""
Inference / Evaluation for TISER with optional RAG ablation.

RAG modes (both expected to HURT — reported as negative finding):
  few_shot         Prepend retrieved solved examples as demonstrations.
  context_stuffing Append retrieved temporal contexts to the sample's own.

Without --use_rag: identical behavior to tiser_lite/evaluation/inference.py.
"""

import argparse
import gc
import json
import os
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path

import torch
from datasets import load_dataset
from peft import PeftModel
from tqdm import tqdm
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    StoppingCriteria,
    StoppingCriteriaList,
)

from utils.io_gpu import balance_by_dataset_name, load_txt_as_string
from utils.metrics import calculate_metrics, clean_output, extract_answer
from utils.prompt import build_prompt
from utils.rag_utils import RAGContextBuilder


# =============================================================================
# Prompt loading
# =============================================================================

@lru_cache(maxsize=16)
def load_prompt_for_lang(prompt_name: str, lang: str) -> str:
    specific = Path(f"data/prompts/{prompt_name}_{lang}.txt")
    fallback = Path(f"data/prompts/{prompt_name}.txt")
    path = specific if specific.exists() else fallback
    if not path.exists():
        raise FileNotFoundError(f"Prompt not found: {specific} or {fallback}")
    return load_txt_as_string(str(path)).strip()


# =============================================================================
# Generation
# =============================================================================

class AnswerTagStopping(StoppingCriteria):
    """Stop when </answer> appears in the generated tail."""

    def __init__(self, tokenizer, prompt_len, lookback=40):
        self.tokenizer = tokenizer
        self.prompt_len = prompt_len
        self.lookback = lookback

    def __call__(self, input_ids, scores, **kwargs):
        gen_ids = input_ids[0][self.prompt_len:]
        if len(gen_ids) < 5:
            return False
        tail = self.tokenizer.decode(gen_ids[-self.lookback:], skip_special_tokens=True)
        return "</answer>" in tail


def _generate(model, tokenizer, prompts, max_new_tokens, use_stop=True):
    inputs = tokenizer(
        prompts, return_tensors="pt", padding=True, truncation=True, max_length=4096,
    ).to(model.device)

    prompt_len = inputs.input_ids.shape[1]
    stopping = None
    if use_stop and inputs.input_ids.shape[0] == 1:
        stopping = StoppingCriteriaList([AnswerTagStopping(tokenizer, prompt_len)])

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.pad_token_id,
            stopping_criteria=stopping,
        )
    return tokenizer.batch_decode(outputs[:, prompt_len:], skip_special_tokens=True)


def generate_batch(model, tokenizer, prompts, args):
    return _generate(model, tokenizer, prompts, args.max_new_tokens)


def generate_iterative(model, tokenizer, prompts, args):
    """Generate, then extend responses that didn't emit </answer>."""
    responses = _generate(model, tokenizer, prompts, args.max_new_tokens)

    for i in range(len(responses)):
        for _ in range(args.max_extensions):
            if "</answer>" in responses[i]:
                break
            extension = _generate(
                model, tokenizer, [prompts[i] + responses[i]], max_new_tokens=256,
            )[0]
            responses[i] += extension

    return responses


# =============================================================================
# Metrics buckets
# =============================================================================

METRIC_NAMES = ["em", "norm_em", "soft_em", "f1", "chrf", "english_leak"]


def empty_bucket():
    return {m: 0.0 for m in METRIC_NAMES} | {"n": 0}


def add_to_bucket(bucket, row):
    for m in METRIC_NAMES:
        bucket[m] += row.get(m, 0)
    bucket["n"] += 1


def fmt_bucket(b):
    n = b["n"]
    if n == 0:
        return "(empty)"
    return (
        f"F1={b['f1']/n:.4f}  chrF={b['chrf']/n:.2f}  "
        f"NormEM={b['norm_em']/n:.4f}  EM={b['em']/n:.4f}  "
        f"SoftEM={b['soft_em']/n:.4f}  EngLeak={b['english_leak']/n:.4f}  N={n}"
    )


# =============================================================================
# Setup helpers
# =============================================================================

def parse_args():
    p = argparse.ArgumentParser(description="TISER inference with optional RAG.")

    # Model
    p.add_argument("--base_model", required=True)
    p.add_argument("--adapter_dir", default=None)

    # Data
    p.add_argument("--test_file", required=True)
    p.add_argument("--output_file", required=True)
    p.add_argument("--max_eval_samples", type=int, default=None)
    p.add_argument("--only_passed", action="store_true", default=True)

    # Generation
    p.add_argument("--strategy", choices=["base", "iterative"], default="iterative")
    p.add_argument("--max_extensions", type=int, default=2)
    p.add_argument("--max_new_tokens", type=int, default=768)
    p.add_argument("--batch_size", type=int, default=1)
    p.add_argument("--prompt_name", type=str, default="tiser_full")
    p.add_argument("--log_every", type=int, default=1)

    # RAG (ablation — expected to hurt)
    p.add_argument("--use_rag", action="store_true")
    p.add_argument("--rag_mode", choices=["few_shot", "context_stuffing"], default="few_shot")
    p.add_argument("--rag_index_dir", type=str, default=None)
    p.add_argument("--rag_top_k", type=int, default=1)
    p.add_argument("--rag_min_score", type=float, default=0.55)
    p.add_argument("--rag_model_name", type=str,
                   default="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

    args = p.parse_args()

    if args.use_rag:
        if not args.rag_index_dir:
            raise ValueError("--use_rag requires --rag_index_dir")
        if not Path(args.rag_index_dir).exists():
            raise FileNotFoundError(f"RAG index not found: {args.rag_index_dir}")

    return args


def print_config(args):
    print(f"Strategy:       {args.strategy}")
    print(f"Max new tokens: {args.max_new_tokens}")
    if args.use_rag:
        print(f"RAG mode:       {args.rag_mode} (ablation)")
        print(f"RAG index:      {args.rag_index_dir}")
        print(f"RAG top-k:      {args.rag_top_k}")
        print(f"RAG min score:  {args.rag_min_score}")
    else:
        print("RAG:            disabled (clean baseline)")


def load_model(args):
    tokenizer = AutoTokenizer.from_pretrained(
        args.base_model, trust_remote_code=True, padding_side="left",
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    print(f"\nLoading model: {args.base_model}")
    compute_dtype = (
        torch.bfloat16
        if torch.cuda.is_available() and torch.cuda.is_bf16_supported()
        else torch.float16
    )
    bnb = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=True,
    )
    base = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        quantization_config=bnb,
        torch_dtype=compute_dtype,
        trust_remote_code=True,
        device_map="auto",
    )

    if args.adapter_dir:
        print(f"Loading adapter: {args.adapter_dir}")
        model = PeftModel.from_pretrained(base, args.adapter_dir)
    else:
        print("No adapter — base model only.")
        model = base

    model.eval()
    return model, tokenizer


def load_data(args):
    ds = load_dataset("json", data_files=args.test_file)["train"]
    if args.only_passed and "validation_status" in ds.column_names:
        ds = ds.filter(lambda x: x["validation_status"] == "PASS")
    if args.max_eval_samples:
        ds = balance_by_dataset_name(
            ds.shuffle(seed=42), category="test", max_samples=args.max_eval_samples,
        )
    data = [dict(x) for x in ds]

    lang_counts = Counter(s.get("language") for s in data)
    if any(lang_counts):
        print(f"\nLanguage distribution: {dict(lang_counts)}")
    print(f"Strategy: '{args.strategy}' | Samples: {len(data)}")
    return data


def apply_rag(ex, base_prompt, rag):
    """
    Returns (prompt, sample, hit_flag) after applying RAG augmentation.
    Called only when rag is not None.
    """
    few_shot_prefix, modified_sample = rag.build(ex)

    if rag.mode == "few_shot" and few_shot_prefix:
        return few_shot_prefix + base_prompt, modified_sample, True

    if rag.mode == "context_stuffing" and (
        modified_sample.get("temporal_context") != ex.get("temporal_context")
    ):
        return base_prompt, modified_sample, True

    return base_prompt, ex, False


# =============================================================================
# Reporting
# =============================================================================

def print_summary(overall, results, args, rag, rag_hits, rag_total):
    print("\n" + "=" * 70)
    print("FINAL OVERALL")
    print("=" * 70)
    print(fmt_bucket(overall))

    if rag is not None:
        hit_pct = 100 * rag_hits / rag_total if rag_total else 0
        print(
            f"\nRAG ({args.rag_mode}): {rag_hits}/{rag_total} samples retrieved "
            f"above min_score={args.rag_min_score} ({hit_pct:.1f}%)"
        )
        if hit_pct < 20:
            print("  ↳ Low hit rate — min_score may be too high.")
        elif hit_pct > 80:
            print("  ↳ High hit rate — noise present for most samples.")

    by_lang = defaultdict(empty_bucket)
    for r in results:
        add_to_bucket(by_lang[r["language"]], r)
    if len(by_lang) > 1:
        print("\nPer-language:")
        for lang in sorted(by_lang):
            print(f"  [{lang}] {fmt_bucket(by_lang[lang])}")

In [ ]:
!sed -n '300,650p' multilingual_rag_tiser/evaluation/inference.py

    by_ds = defaultdict(empty_bucket)
    for r in results:
        add_to_bucket(by_ds[r.get("dataset_name", "unknown")], r)
    if len(by_ds) > 1:
        print("\nPer-dataset:")
        for ds in sorted(by_ds):
            print(f"  [{ds}] {fmt_bucket(by_ds[ds])}")

    print("=" * 70)
    print(f"Results saved to: {args.output_file}")


# =============================================================================
# Main
# =============================================================================

def main():
    args = parse_args()
    print_config(args)

    model, tokenizer = load_model(args)

    rag = None
    if args.use_rag:
        rag = RAGContextBuilder(
            index_dir=args.rag_index_dir,
            model_name=args.rag_model_name,
            top_k=args.rag_top_k,
            min_score=args.rag_min_score,
            mode=args.rag_mode,
        )

    data = load_data(args)
    generate_fn = generate_iterative if args.strategy == "iterative" else generate_batch

    results = []
    overall = empty_bucket()
    rag_total = 0
    rag_hits = 0

    for i in tqdm(range(0, len(data), args.batch_size)):
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            gc.collect()

        batch = data[i:i + args.batch_size]
        lang = batch[0].get("language", "en")
        base_prompt = load_prompt_for_lang(args.prompt_name, lang)

        prompts = []
        for ex in batch:
            if rag is not None:
                rag_total += 1
                prompt, sample, hit = apply_rag(ex, base_prompt, rag)
                if hit:
                    rag_hits += 1
            else:
                prompt, sample = base_prompt, ex
            prompts.append(build_prompt(sample, prompt=prompt))

        decoded = generate_fn(model, tokenizer, prompts, args)

        for j, pred in enumerate(decoded):
            ex = batch[j]
            full = clean_output("<reasoning>" + pred)
            extracted = extract_answer(full)
            metrics = calculate_metrics(
                extracted,
                [str(ex.get("answer", ""))],
                gold_en=str(ex.get("answer_en", "")),
            )
            add_to_bucket(overall, metrics)

            results.append({
                "question_id": ex.get("question_id"),
                "dataset_name": ex.get("dataset_name", ""),
                "language": ex.get("language", "en"),
                "gold_target": str(ex.get("answer", "")),
                "gold_en": str(ex.get("answer_en", "")),
                "extracted": extracted,
                "model_output": full,
                "rag_used": rag is not None,
                "rag_mode": args.rag_mode if rag is not None else None,
                **metrics,
            })

            if overall["n"] % args.log_every == 0:
                n = overall["n"]
                tqdm.write(
                    f"Step {n} | F1={overall['f1']/n:.4f}  "
                    f"chrF={overall['chrf']/n:.2f}  "
                    f"NormEM={overall['norm_em']/n:.4f}  "
                    f"EM={overall['em']/n:.4f}"
                )

    os.makedirs(os.path.dirname(args.output_file) or ".", exist_ok=True)
    with open(args.output_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print_summary(overall, results, args, rag, rag_hits, rag_total)


if __name__ == "__main__":
    main()

In [ ]:
import json

repo_test = []

with open("data/TISER_test.json", "r", encoding="utf-8") as f:
    for line in f:
        repo_test.append(json.loads(line))

print(len(repo_test))
print(repo_test[0].keys())
print(repo_test[0])

22014
dict_keys(['dataset_name', 'question_id', 'question', 'prompt', 'answer'])
{'dataset_name': 'tgqa_test', 'question_id': 'story500_Q0_0', 'question': 'Which event started first, (Chris Evans was married to Oliver Jensen) or (Chris Evans was born in Bristol, Connecticut)?', 'prompt': '### Question:\n    \n    You are an AI assistant that uses a Chain of Thought (CoT) approach with reflection to answer queries. Follow these steps:\n\nStep 1. Reason through the problem step by step within the <reasoning> tags.\nStep 2. Given your previous reasoning, identify relevant temporal events in the given context for answering the given question within <timeline> tags. Assume relations in the context are unidirectional.\nStep 3. Reflect on your reasoning and the timeline to check for any errors or improvements within the <reflection> tags.\nStep 4. Make any necessary adjustments based on your reflection. If there is additional reasoning required, go back to Step 1 (reason through the problem step-by-step), otherwise move to the next step (Step 5).\nStep 5. Provide your final, concise answer within the <answer> tags. If the answer is a number, just output the number nothing else. Otherwise output the entity or event, without any additional comments.\n\nImportant: The <reasoning>, <reflection> and <timeline> sections are for your internal reasoning process. All the reflection and the timeline have to be contained inside the thinking section.\nDo not use enumerations or lists when writing, use plain text instead such as paragraphs.\nThe response to the query must be entirely contained within the <answer> tags.\n\nUse the following format for your response:\n    \n    <reasoning> \n[Your step-by-step reasoning goes here. This is your internal thought process.]\n<timeline> \n[Relevant temporal events for answering the given question.]\n</timeline> \n<reflection> \n[Your reflection on your reasoning, checking for errors, improvements or changes required]\n</reflection> \n[Any adjustments to your thinking based on your reflection]\n</reasoning> \n<answer> \n[Your final, concise answer to the query.]\n</answer>\n    \n    Question: Which event started first, (Chris Evans was married to Oliver Jensen) or (Chris Evans was born in Bristol, Connecticut)?\n    \n    Temporal context: (Chris Evans was born in Bristol, Connecticut) starts at 1948. (Oliver Jensen was born in Bristol, Connecticut) starts at 1948. (Chris Evans was married to Oliver Jensen) starts at 1970. (Oliver Jensen was married to Chris Evans) starts at 1970. (Chris Evans owned Pearl Network) starts at 2005. (Chris Evans won prize Victory Achievement Award) starts at 2007. (Chris Evans was married to Oliver Jensen) ends at 2010. (Oliver Jensen was married to Chris Evans) ends at 2010. (Chris Evans owned Pearl Network) ends at 2013\n    \n    ### Answer:', 'answer': 'Chris Evans was born in Bristol, Connecticut'}

In [ ]:
!sed -n '1,320p' multilingual_rag_tiser/training/train_qlora.py

#!/usr/bin/env python3
"""
QLoRA Training Script — Class-Based Refactor (8GB VRAM + Validation Safe)

Key features:
- 8GB-friendly defaults
- 4-bit QLoRA
- Validation split support
- Best checkpoint by eval loss
- CPU offload support
- group_by_length enabled
"""

import argparse
import os
from typing import Any, List, Optional, Dict
from dataclasses import dataclass

import torch
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    BitsAndBytesConfig,
    PreTrainedTokenizer,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

from utils.io_gpu import balance_by_dataset_name, load_prompt_for_lang
from utils.prompt import build_prompt

# -------------------------
# OPTIMIZATION FLAGS
# -------------------------
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

if torch.cuda.is_available():
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True


# ─────────────────────────────────────────────
# Data Collator
# ─────────────────────────────────────────────

@dataclass
class DataCollatorForCausalLMWithPadding:
    """Pads input_ids / attention_mask and aligns labels with -100 fill."""

    tokenizer: Any

    def __call__(self, features: List[Dict]) -> Dict[str, torch.Tensor]:
        labels = [f["labels"] for f in features]
        features_no_labels = [{k: v for k, v in f.items() if k != "labels"} for f in features]

        batch = self.tokenizer.pad(features_no_labels, return_tensors="pt")
        max_len = batch["input_ids"].shape[1]

        padded_labels = [lbl + [-100] * (max_len - len(lbl)) for lbl in labels]
        batch["labels"] = torch.tensor(padded_labels, dtype=torch.long)
        return batch


# ─────────────────────────────────────────────
# Dataset Handler
# ─────────────────────────────────────────────

class QLoRADatasetHandler:
    """Loads, filters, tokenizes and splits the dataset."""

    def __init__(self, args: argparse.Namespace, tokenizer: PreTrainedTokenizer):
        self.args = args
        self.tokenizer = tokenizer

    # ------------------------------------------------------------------
    def load(self) -> Dataset:
        print(f"Loading dataset from: {self.args.train_file}")
        dataset = load_dataset("json", data_files=self.args.train_file)["train"]

        if self.args.only_passed and "validation_status" in dataset.column_names:
            dataset = dataset.filter(lambda x: x["validation_status"] == "PASS")
            print(f"Filtered to PASS samples: {len(dataset)}")

        if self.args.max_train_samples:
            print(f"Balancing dataset to max {self.args.max_train_samples} samples...")
            dataset = balance_by_dataset_name(
                dataset.shuffle(seed=42),
                category="train",
                max_samples=self.args.max_train_samples,
            )

        if isinstance(dataset, list):
            print("Converting list back to Hugging Face Dataset...")
            dataset = Dataset.from_list(dataset)

        return dataset

    # ------------------------------------------------------------------
    def _preprocess(self, ex: Dict) -> Dict:
        lang = ex.get("language") or "en"
        prompt = load_prompt_for_lang(self.args.prompt_name, lang)
        full_prompt = build_prompt(ex, prompt=prompt)

        if not full_prompt or not full_prompt.strip():
            raise ValueError(
                f"Empty prompt generated with prompt_name={self.args.prompt_name}. "
                f"Example keys: {list(ex.keys())}"
            )

        output = (ex.get("output", "") or ex.get("answer", "") or "").strip()

        prompt_tokens = self.tokenizer(full_prompt, add_special_tokens=False)["input_ids"]
        output_tokens = self.tokenizer(
            output + self.tokenizer.eos_token,
            add_special_tokens=False,
        )["input_ids"]

        input_ids = prompt_tokens + output_tokens
        labels = [-100] * len(prompt_tokens) + output_tokens

        if len(input_ids) > self.args.max_length:
            input_ids = input_ids[: self.args.max_length]
            labels = labels[: self.args.max_length]

        # Drop samples where truncation removed all output tokens
        if all(x == -100 for x in labels):
            return {"input_ids": [], "labels": [], "attention_mask": []}

        return {
            "input_ids": input_ids,
            "labels": labels,
            "attention_mask": [1] * len(input_ids),
        }

    # ------------------------------------------------------------------
    @staticmethod
    def _has_valid_labels(example: Dict) -> bool:
        return any(x != -100 for x in example["labels"])

    # ------------------------------------------------------------------
    def tokenize(self, dataset: Dataset) -> Dataset:
        print("Tokenizing dataset...")
        dataset = dataset.map(
            self._preprocess,
            remove_columns=dataset.column_names,
            desc="Tokenizing",
        )
        dataset = dataset.filter(lambda x: len(x["input_ids"]) > 0)

        if len(dataset) == 0:
            raise ValueError("No valid samples remain after preprocessing.")

        return dataset

    # ------------------------------------------------------------------
    def split(self, dataset: Dataset):
        """Returns (train_dataset, eval_dataset | None)."""
        if self.args.validation_split > 0 and len(dataset) > 10:
            splits = dataset.train_test_split(test_size=self.args.validation_split, seed=42)
            train_dataset = splits["train"]
            eval_dataset = splits["test"]

            before = len(eval_dataset)
            eval_dataset = eval_dataset.filter(self._has_valid_labels)
            removed = before - len(eval_dataset)
            if removed:
                print(f"Removed {removed} bad samples from val set")

            if len(eval_dataset) == 0:
                print("WARNING: val set empty after filtering — disabling evaluation")
                eval_dataset = None

            print(f"Train samples:      {len(train_dataset)}")
            print(f"Validation samples: {len(eval_dataset) if eval_dataset else 0}")
            return train_dataset, eval_dataset

        print(f"Train samples: {len(dataset)}")
        print("No validation split used.")
        return dataset, None

    # ------------------------------------------------------------------
    def prepare(self):
        """Full pipeline: load → tokenize → split."""
        raw = self.load()
        tokenized = self.tokenize(raw)
        return self.split(tokenized)


# ─────────────────────────────────────────────
# Model Builder
# ─────────────────────────────────────────────

class QLoRAModelBuilder:
    """Loads the base model in 4-bit and wraps it with LoRA adapters."""

    def __init__(self, args: argparse.Namespace):
        self.args = args

    # ------------------------------------------------------------------
    @staticmethod
    def _find_lora_targets(model) -> List[str]:
        names = {n.split(".")[-1] for n, _ in model.named_modules()}
        preferred = [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ]
        return [m for m in preferred if m in names]

    # ------------------------------------------------------------------
    def _bnb_config(self) -> BitsAndBytesConfig:
        return BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=torch.float16,
        )

    # ------------------------------------------------------------------
    def build(self):
        print("Loading model in 4-bit...")
        model = AutoModelForCausalLM.from_pretrained(
            self.args.model_name,
            device_map="auto",
            max_memory={
                0: f"{self.args.gpu_memory_gb}GiB",
                "cpu": f"{self.args.cpu_memory_gb}GiB",
            },
            quantization_config=self._bnb_config(),
            trust_remote_code=True,
            low_cpu_mem_usage=True,
            torch_dtype=torch.float16,
        )

        model.config.use_cache = False
        model = prepare_model_for_kbit_training(
            model,
            use_gradient_checkpointing=(self.args.gradient_checkpointing == 1),
        )

        targets = self._find_lora_targets(model)
        print(f"Targeting modules for LoRA: {targets}")
        if not targets:
            raise ValueError("Could not find LoRA target modules in the model.")

        lora_config = LoraConfig(
            r=self.args.lora_r,
            lora_alpha=self.args.lora_alpha,
            lora_dropout=self.args.lora_dropout,
            target_modules=targets,
            bias="none",
            task_type="CAUSAL_LM",
        )

        model = get_peft_model(model, lora_config)
        model.print_trainable_parameters()
        return model


# ─────────────────────────────────────────────
# Trainer Builder
# ─────────────────────────────────────────────

class QLoRATrainerBuilder:
    """Assembles the HuggingFace Trainer from model, datasets and args."""

    def __init__(
        self,
        args: argparse.Namespace,
        model,
        tokenizer: PreTrainedTokenizer,
        train_dataset: Dataset,
        eval_dataset: Optional[Dataset],
    ):
        self.args = args
        self.model = model
        self.tokenizer = tokenizer
        self.train_dataset = train_dataset
        self.eval_dataset = eval_dataset

    # ------------------------------------------------------------------
    def _training_args(self) -> TrainingArguments:
        has_eval = self.eval_dataset is not None
        return TrainingArguments(
            output_dir=self.args.output_dir,
            num_train_epochs=self.args.epochs,
            learning_rate=self.args.lr,
            per_device_train_batch_size=self.args.per_device_batch_size,
            per_device_eval_batch_size=1,
            gradient_accumulation_steps=self.args.grad_accum,
            bf16=False,
            fp16=True,
            optim="paged_adamw_8bit",
            logging_steps=self.args.logging_steps,
            save_strategy="steps",
            save_steps=self.args.eval_steps,
            eval_strategy="steps" if has_eval else "no",
            eval_steps=self.args.eval_steps if has_eval else None,
            save_total_limit=2,
            gradient_checkpointing=(self.args.gradient_checkpointing == 1),
            dataloader_num_workers=self.args.dataloader_num_workers,
            report_to="none",
            remove_unused_columns=False,
            ddp_find_unused_parameters=False,
            load_best_model_at_end=has_eval,
            metric_for_best_model="eval_loss",
            greater_is_better=False,
        )

    # ------------------------------------------------------------------
    def build(self) -> Trainer:
        return Trainer(
            model=self.model,
            args=self._training_args(),
            train_dataset=self.train_dataset,
            eval_dataset=self.eval_dataset,
            data_collator=DataCollatorForCausalLMWithPadding(self.tokenizer),
        )

In [ ]:
import re

def extract_temporal_context_from_prompt(prompt):
    match = re.search(
        r"Temporal context:\s*(.*?)\s*### Answer:",
        prompt,
        re.DOTALL
    )
    if match:
        return match.group(1).strip()
    return ""

test_ex = repo_test[0].copy()
test_ex["temporal_context"] = extract_temporal_context_from_prompt(test_ex["prompt"])

print(test_ex.keys())
print(test_ex["temporal_context"][:500])

dict_keys(['dataset_name', 'question_id', 'question', 'prompt', 'answer', 'temporal_context'])
(Chris Evans was born in Bristol, Connecticut) starts at 1948. (Oliver Jensen was born in Bristol, Connecticut) starts at 1948. (Chris Evans was married to Oliver Jensen) starts at 1970. (Oliver Jensen was married to Chris Evans) starts at 1970. (Chris Evans owned Pearl Network) starts at 2005. (Chris Evans won prize Victory Achievement Award) starts at 2007. (Chris Evans was married to Oliver Jensen) ends at 2010. (Oliver Jensen was married to Chris Evans) ends at 2010. (Chris Evans owned Pearl

In [ ]:
from utils.prompt import build_prompt
from utils.io_gpu import load_prompt_for_lang

sample = repo_test[0].copy()

sample["temporal_context"] = extract_temporal_context_from_prompt(sample["prompt"])

repo_instruction = load_prompt_for_lang("tiser_full", "en")

rebuilt_prompt = build_prompt(
    sample,
    prompt=repo_instruction
)

print("="*80)
print("REBUILT PROMPT")
print("="*80)
print(rebuilt_prompt)

print("\n")
print("="*80)
print("ORIGINAL PROMPT")
print("="*80)
print(sample["prompt"])

================================================================================
REBUILT PROMPT
================================================================================
You are an AI assistant that uses a Chain of Thought (CoT) approach with reflection to answer queries. Follow the steps below:

Step 1: Reason through the problem step by step within the <reasoning> section.

Step 2: Based on your reasoning, identify the relevant temporal events needed to answer the given question within the <timeline> section. Assume that temporal relations in the context are unidirectional.

Step 3: Review your reasoning and the constructed timeline to check for any errors or possible improvements within the <reflection> section.

Step 4: If necessary, revise your reasoning based on your reflection. If additional reasoning is required, return to Step 1; otherwise, proceed to the next step.

Step 5: Provide the final, concise answer only within the <answer> section. If the answer is a number, output only the number and nothing else. Otherwise, output only the entity or event name without any additional explanation.

Additional instructions:
• If this is during data generation, perform your reasoning knowing that the correct answer is X.
• The <reasoning>, <timeline>, and <reflection> sections are for internal reasoning only.
• Do not use enumerations or lists when writing; use plain text in paragraph form.
• The response to the query must be entirely contained within the <answer> section.

Response format:

<reasoning>
[Your step-by-step reasoning]
<timeline>
[Relevant temporal events]
</timeline>
<reflection>
[Reflection on the reasoning and possible corrections]
</reflection>
</reasoning>

<answer>
[Final concise answer]
</answer>

Context:
(Chris Evans was born in Bristol, Connecticut) starts at 1948. (Oliver Jensen was born in Bristol, Connecticut) starts at 1948. (Chris Evans was married to Oliver Jensen) starts at 1970. (Oliver Jensen was married to Chris Evans) starts at 1970. (Chris Evans owned Pearl Network) starts at 2005. (Chris Evans won prize Victory Achievement Award) starts at 2007. (Chris Evans was married to Oliver Jensen) ends at 2010. (Oliver Jensen was married to Chris Evans) ends at 2010. (Chris Evans owned Pearl Network) ends at 2013

Question:
Which event started first, (Chris Evans was married to Oliver Jensen) or (Chris Evans was born in Bristol, Connecticut)?




================================================================================
ORIGINAL PROMPT
================================================================================
### Question:

    You are an AI assistant that uses a Chain of Thought (CoT) approach with reflection to answer queries. Follow these steps:

Step 1. Reason through the problem step by step within the <reasoning> tags.
Step 2. Given your previous reasoning, identify relevant temporal events in the given context for answering the given question within <timeline> tags. Assume relations in the context are unidirectional.
Step 3. Reflect on your reasoning and the timeline to check for any errors or improvements within the <reflection> tags.
Step 4. Make any necessary adjustments based on your reflection. If there is additional reasoning required, go back to Step 1 (reason through the problem step-by-step), otherwise move to the next step (Step 5).
Step 5. Provide your final, concise answer within the <answer> tags. If the answer is a number, just output the number nothing else. Otherwise output the entity or event, without any additional comments.

Important: The <reasoning>, <reflection> and <timeline> sections are for your internal reasoning process. All the reflection and the timeline have to be contained inside the thinking section.
Do not use enumerations or lists when writing, use plain text instead such as paragraphs.
The response to the query must be entirely contained within the <answer> tags.

Use the following format for your response:

    <reasoning>
[Your step-by-step reasoning goes here. This is your internal thought process.]
<timeline>
[Relevant temporal events for answering the given question.]
</timeline>
<reflection>
[Your reflection on your reasoning, checking for errors, improvements or changes required]
</reflection>
[Any adjustments to your thinking based on your reflection]
</reasoning>
<answer>
[Your final, concise answer to the query.]
</answer>

    Question: Which event started first, (Chris Evans was married to Oliver Jensen) or (Chris Evans was born in Bristol, Connecticut)?

    Temporal context: (Chris Evans was born in Bristol, Connecticut) starts at 1948. (Oliver Jensen was born in Bristol, Connecticut) starts at 1948. (Chris Evans was married to Oliver Jensen) starts at 1970. (Oliver Jensen was married to Chris Evans) starts at 1970. (Chris Evans owned Pearl Network) starts at 2005. (Chris Evans won prize Victory Achievement Award) starts at 2007. (Chris Evans was married to Oliver Jensen) ends at 2010. (Oliver Jensen was married to Chris Evans) ends at 2010. (Chris Evans owned Pearl Network) ends at 2013

    ### Answer:

In [ ]:
print("balanced_500 exists:", "balanced_500" in globals())
print("official_balanced_500 exists:", "official_balanced_500" in globals())
print("qwen_baseline_500 exists:", "qwen_baseline_500" in globals())

balanced_500 exists: True
official_balanced_500 exists: False
qwen_baseline_500 exists: True

In [ ]:
repo_prompt_examples = []

for ex in balanced_500[:20]:
    new_ex = ex.copy()
    new_ex["temporal_context"] = extract_temporal_context_from_prompt(new_ex["prompt"])
    repo_prompt_examples.append(new_ex)

print("Prepared:", len(repo_prompt_examples))
print(repo_prompt_examples[0].keys())
print(repo_prompt_examples[0]["temporal_context"][:300])

Prepared: 20
dict_keys(['dataset_name', 'question_id', 'question', 'prompt', 'answer', 'temporal_context'])
(Chris Evans was born in Bristol, Connecticut) starts at 1948. (Oliver Jensen was born in Bristol, Connecticut) starts at 1948. (Chris Evans was married to Oliver Jensen) starts at 1970. (Oliver Jensen was married to Chris Evans) starts at 1970. (Chris Evans owned Pearl Network) starts at 2005. (Chr

In [ ]:
repo_prompt_results_20 = []

repo_instruction = load_prompt_for_lang("tiser_full", "en")

for idx, sample in enumerate(repo_prompt_examples):

    prompt = build_prompt(sample, prompt=repo_instruction)

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=512,
        do_sample=False,
        repetition_penalty=1.1
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    response = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    prediction = extract_answer(response)

    repo_prompt_results_20.append({
        "index": idx,
        "dataset_name": sample["dataset_name"],
        "question": sample["question"],
        "ground_truth": sample["answer"],
        "prediction": prediction,
        "full_response": response
    })

    print(f"Processed {idx+1}/20")

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Processed 1/20
Processed 2/20
Processed 3/20
Processed 4/20
Processed 5/20
Processed 6/20
Processed 7/20
Processed 8/20
Processed 9/20
Processed 10/20
Processed 11/20
Processed 12/20
Processed 13/20
Processed 14/20
Processed 15/20
Processed 16/20
Processed 17/20
Processed 18/20
Processed 19/20
Processed 20/20

In [ ]:
correct = 0
f1_scores = []

for r in repo_prompt_results_20:
    if normalize_for_eval(r["prediction"]) == normalize_for_eval(r["ground_truth"]):
        correct += 1

    f1_scores.append(
        repo_f1(
            r["prediction"],
            r["ground_truth"]
        )
    )

print("NormEM:", correct / len(repo_prompt_results_20))
print("F1:", sum(f1_scores) / len(f1_scores))

NormEM: 0.8
F1: 0.75

In [ ]:
!sed -n '1,220p' multilingual_rag_tiser/training/run_train.sh

#!/usr/bin/env bash
set -euo pipefail

export PYTHONPATH="$(pwd):${PYTHONPATH:-}"
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

MODEL="${1:-}"              # qwen
LANG="${2:-}"               # en, it, de, fa, en_it_de_mixed_15000, mixed
PROMPT_NAME="${3:-tiser_full}"
MAX_SAMPLES="${4:-2000}"        # optional

if [[ -z "$MODEL" || -z "$LANG" ]]; then
  echo "Usage:"
  echo "  bash multilingual_tiser/training/run_train.sh qwen en tiser_full 15000"
  echo "  bash multilingual_tiser/training/run_train.sh qwen it tiser_full 15000"
  echo "  bash multilingual_tiser/training/run_train.sh qwen de tiser_full 15000"
  echo "  bash multilingual_tiser/training/run_train.sh qwen en_it_de_mixed_15000 tiser_full"
  echo "  bash multilingual_tiser/training/run_train.sh qwen mixed tiser_full 15000"
  exit 1
fi

# -------------------------
# Base model
# -------------------------
if [[ "$MODEL" == "qwen" ]]; then
  MODEL_NAME="Qwen/Qwen2.5-3B-Instruct"
else
  echo "ERROR: unsupported model type: $MODEL"
  echo "Currently supported: qwen"
  exit 1
fi

# -------------------------
# Select train file
# -------------------------
TRAIN_FILE=""

if [[ "$LANG" == "en" ]]; then
  TRAIN_FILE="data/splits/train/TISER_train_en.json"

elif [[ "$LANG" == "it" ]]; then
  # Use passed file if it exists, otherwise fallback to raw translated file
  if [[ -f "data/splits/train/it/TISER_train_it_passed.json" ]]; then
    TRAIN_FILE="data/splits/train/it/TISER_train_it_passed.json"
  else
    TRAIN_FILE="data/splits/train/TISER_train_it.json"
  fi

elif [[ "$LANG" == "de" ]]; then
  if [[ -f "data/splits/train/de/TISER_train_de_passed.json" ]]; then
    TRAIN_FILE="data/splits/train/de/TISER_train_de_passed.json"
  else
    TRAIN_FILE="data/splits/train/TISER_train_de.json"
  fi

elif [[ "$LANG" == "fa" ]]; then
  if [[ -f "data/splits/train/fa/TISER_train_fa_passed.json" ]]; then
    TRAIN_FILE="data/splits/train/fa/TISER_train_fa_passed.json"
  else
    TRAIN_FILE="data/splits/train/TISER_train_fa.json"
  fi

elif [[ "$LANG" == "mixed" ]]; then
  # Default mixed file based on MAX_SAMPLES
  if [[ -z "$MAX_SAMPLES" ]]; then
    echo "ERROR: for LANG=mixed you should pass MAX_SAMPLES."
    echo "Example:"
    echo "  bash multilingual_tiser/training/run_train.sh qwen mixed tiser_full 15000"
    exit 1
  fi

  TRAIN_FILE="data/splits/train/TISER_train_en_it_de_mixed_${MAX_SAMPLES}.json"

elif [[ "$LANG" == *"mixed"* ]]; then
  # Example:
  # LANG=en_it_mixed_2000
  # LANG=en_it_de_mixed_15000
  TRAIN_FILE="data/splits/train/TISER_train_${LANG}.json"

else
  echo "ERROR: unknown language/dataset name: $LANG"
  exit 1
fi

if [[ ! -f "$TRAIN_FILE" ]]; then
  echo "ERROR: train file not found:"
  echo "$TRAIN_FILE"
  echo
  echo "Available train files:"
  ls -lh data/splits/train/*.json 2>/dev/null || true
  echo
  echo "Available scored files:"
  ls -lh data/splits/train/*/*.json 2>/dev/null || true
  exit 1
fi

# -------------------------
# max samples arg
# -------------------------
MAX_SAMPLES_ARG=""
if [[ -n "$MAX_SAMPLES" ]]; then
  MAX_SAMPLES_ARG="--max_train_samples $MAX_SAMPLES"
fi

# -------------------------
# Output dir
# -------------------------
SAMPLE_NAME="${MAX_SAMPLES:-full}"
OUT_DIR="experiments/${MODEL}/${LANG}_${PROMPT_NAME}_${SAMPLE_NAME}_8gb_val_qlora"
mkdir -p "$OUT_DIR"

# -------------------------
# 8GB-safe defaults
# -------------------------
EPOCHS=2
LR=3e-4
MAX_LEN=1536

LORA_R=16
LORA_ALPHA=32
LORA_DROPOUT=0.05

PER_DEVICE_BS=1
GRAD_ACCUM=16

VAL_SPLIT=0.1

# Safe eval/save steps
if [[ -n "$MAX_SAMPLES" && "$MAX_SAMPLES" -gt 0 ]]; then
  EVAL_STEPS=$(( MAX_SAMPLES / 20 ))

  if [[ "$EVAL_STEPS" -lt 10 ]]; then
    EVAL_STEPS=10
  fi
else
  EVAL_STEPS=500
fi

echo "=============================="
echo " STARTING 8GB VRAM TRAINING"
echo "Model Type    : $MODEL"
echo "Model         : $MODEL_NAME"
echo "Prompt        : $PROMPT_NAME"
echo "Lang/Dataset  : $LANG"
echo "Train File    : $TRAIN_FILE"
echo "Output Dir    : $OUT_DIR"
echo "Max Samples   : ${MAX_SAMPLES:-all}"
echo "Max Length    : $MAX_LEN"
echo "LoRA Rank     : $LORA_R"
echo "LoRA Alpha    : $LORA_ALPHA"
echo "Batch Size    : $PER_DEVICE_BS"
echo "Grad Accum    : $GRAD_ACCUM"
echo "Validation    : $VAL_SPLIT"
echo "Eval Steps    : $EVAL_STEPS"
echo "Save Steps    : $EVAL_STEPS"
echo "=============================="

python multilingual_rag_tiser/training/train_qlora.py \
  --model_name "$MODEL_NAME" \
  --train_file "$TRAIN_FILE" \
  --output_dir "$OUT_DIR" \
  --epochs "$EPOCHS" \
  --lr "$LR" \
  --max_length "$MAX_LEN" \
  --lora_r "$LORA_R" \
  --lora_alpha "$LORA_ALPHA" \
  --lora_dropout "$LORA_DROPOUT" \
  --per_device_batch_size "$PER_DEVICE_BS" \
  --grad_accum "$GRAD_ACCUM" \
  --save_steps "$EVAL_STEPS" \
  --logging_steps 10 \
  --eval_steps "$EVAL_STEPS" \
  --validation_split "$VAL_SPLIT" \
  --dataloader_num_workers 0 \
  --gradient_checkpointing 1 \
  --gpu_memory_gb 7 \
  --cpu_memory_gb 16 \
  $MAX_SAMPLES_ARG \
  --only_passed \
  --prompt_name "$PROMPT_NAME"

In [ ]:
!sed -n '1,220p' multilingual_rag_tiser/evaluation/run_eval_rag.sh

#!/usr/bin/env bash
set -euo pipefail

export PYTHONPATH="$(pwd):${PYTHONPATH:-}"

MODEL_TYPE="${1:-}"
LANG="${2:-}"
ADAPTER_DIR="${3:-none}"
STRATEGY="${4:-iterative}"
PROMPT_NAME="${5:-tiser_full}"
MAX_SAMPLES="${6:-500}"

if [[ -z "$MODEL_TYPE" || -z "$LANG" ]]; then
    cat <<EOF
Usage:
  bash run_eval_rag.sh <qwen|mistral> <en|it|de|fr|fa|mixed> \\
    [adapter|none] [base|iterative] [prompt] [max_samples]

Env overrides:
  USE_RAG=0|1          Toggle RAG (default 1)
  RAG_MODE=few_shot|context_stuffing   (default few_shot)
  RAG_TOP_K=1          Exemplars (1–2)
  RAG_MIN_SCORE=0.60   Cosine threshold (NOT 0.9)
  RAG_INDEX_DIR=...    Override index dir
  RAG_TRAIN_FILE=...   Override train file for index build
EOF
    exit 1
fi

# ---- RAG defaults ----
USE_RAG="${USE_RAG:-1}"
RAG_MODE="${RAG_MODE:-few_shot}"
RAG_TOP_K="${RAG_TOP_K:-1}"
RAG_MIN_SCORE="${RAG_MIN_SCORE:-0.60}"
RAG_EMBED_MODEL="${RAG_EMBED_MODEL:-sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2}"

# ---- Base model ----
case "$MODEL_TYPE" in
    qwen)    BASE_MODEL="Qwen/Qwen2.5-3B-Instruct" ;;
    mistral) BASE_MODEL="mistralai/Mistral-7B-Instruct-v0.2" ;;
    *) echo "ERROR: unknown model type: $MODEL_TYPE"; exit 1 ;;
esac

# ---- Test file ----
find_first() {
    for f in "$@"; do [[ -f "$f" ]] && { echo "$f"; return 0; }; done
    return 1
}

TEST_FILE="${TEST_FILE:-$(find_first \
    "data/splits/test/${LANG}/TISER_test_${LANG}_passed.json" \
    "data/splits/test/${LANG}/TISER_test_${LANG}.json" \
    "data/splits/test/TISER_test_${LANG}.json")}" || {
        echo "ERROR: no test file found for lang=$LANG"; exit 1;
    }

# ---- RAG train file ----
if [[ -z "${RAG_TRAIN_FILE:-}" ]]; then
    if [[ "$LANG" == "mixed" ]]; then
        RAG_TRAIN_FILE=$(find_first \
            "data/splits/train/TISER_train_de_it_fr_en_mixed.json" \
            "data/splits/train/TISER_train_en_it_de_mixed.json" \
            "data/splits/train/TISER_train_mixed.json") || true
    elif [[ "$LANG" == "it" ]]; then
        RAG_TRAIN_FILE=$(find_first \
            "data/splits/train/it/TISER_train_it_passed.json" \
            "data/splits/train/TISER_train_it.json") || true
    else
        RAG_TRAIN_FILE="data/splits/train/TISER_train_${LANG}.json"
    fi
fi

RAG_INDEX_DIR="${RAG_INDEX_DIR:-data/rag/train_${LANG}}"

# ---- Output ----
TIMESTAMP="$(date +"%Y%m%d_%H%M%S")"
if [[ "$ADAPTER_DIR" == "none" ]]; then
    RESULTS_DIR="experiments/${MODEL_TYPE}_base/results"
    MODEL_NAME="base"
    ADAPTER_ARG=()
else
    ADAPTER_CLEAN="${ADAPTER_DIR%/}"
    RESULTS_DIR="${ADAPTER_CLEAN}/results"
    MODEL_NAME="$(basename "$ADAPTER_CLEAN")"
    ADAPTER_ARG=(--adapter_dir "$ADAPTER_DIR")
fi
mkdir -p "$RESULTS_DIR"

RAG_SUFFIX=""
[[ "$USE_RAG" == "1" ]] && RAG_SUFFIX="_rag_${RAG_MODE}_k${RAG_TOP_K}_s${RAG_MIN_SCORE}"

GEN_OUTPUT="${RESULTS_DIR}/gen_${MODEL_NAME}_${LANG}_${STRATEGY}_${PROMPT_NAME}${RAG_SUFFIX}_${TIMESTAMP}.json"

MAX_SAMPLES_ARG=()
[[ -n "$MAX_SAMPLES" && "$MAX_SAMPLES" != "0" ]] && \
    MAX_SAMPLES_ARG=(--max_eval_samples "$MAX_SAMPLES")

SCRIPTS_DIR="multilingual_rag_tiser"
INFERENCE_SCRIPT="${SCRIPTS_DIR}/evaluation/inference.py"
BUILD_INDEX_SCRIPT="${SCRIPTS_DIR}/rag/build_rag_index.py"

# ---- Print config ----
cat <<EOF
======================================================================
TISER RAG Evaluation
======================================================================
Model:       $BASE_MODEL
Adapter:     $ADAPTER_DIR
Language:    $LANG
Strategy:    $STRATEGY
Prompt:      $PROMPT_NAME
Max samples: $MAX_SAMPLES
Test file:   $TEST_FILE
Output:      $GEN_OUTPUT

RAG enabled: $USE_RAG
EOF
if [[ "$USE_RAG" == "1" ]]; then
    cat <<EOF
RAG mode:    $RAG_MODE
RAG train:   ${RAG_TRAIN_FILE:-<none>}
RAG index:   $RAG_INDEX_DIR
RAG top-k:   $RAG_TOP_K
RAG score:   $RAG_MIN_SCORE  (cosine; 0.9 is too high)
RAG model:   $RAG_EMBED_MODEL
EOF
fi
echo "======================================================================"

# ---- Safety checks ----
[[ -f "$INFERENCE_SCRIPT" ]] || { echo "ERROR: missing $INFERENCE_SCRIPT"; exit 1; }
[[ -f "$TEST_FILE" ]] || { echo "ERROR: missing $TEST_FILE"; exit 1; }

# ---- Build RAG index if needed ----
RAG_ARG=()
if [[ "$USE_RAG" == "1" ]]; then
    if [[ ! -f "${RAG_INDEX_DIR}/index.faiss" || ! -f "${RAG_INDEX_DIR}/documents.json" ]]; then
        [[ -f "${RAG_TRAIN_FILE:-}" ]] || {
            echo "ERROR: RAG index missing and RAG_TRAIN_FILE not set/found."
            exit 1
        }
        echo ""
        echo "Building RAG index from: $RAG_TRAIN_FILE"

        LANG_ARG=()
        [[ "$LANG" != "mixed" ]] && LANG_ARG=(--language "$LANG")

        python "$BUILD_INDEX_SCRIPT" \
            --input "$RAG_TRAIN_FILE" \
            --output_dir "$RAG_INDEX_DIR" \
            --model_name "$RAG_EMBED_MODEL" \
            "${LANG_ARG[@]}"
    else
        echo "RAG index exists: $RAG_INDEX_DIR"
    fi

    RAG_ARG=(
        --use_rag
        --rag_index_dir "$RAG_INDEX_DIR"
        --rag_top_k "$RAG_TOP_K"
        --rag_min_score "$RAG_MIN_SCORE"
        --rag_model_name "$RAG_EMBED_MODEL"
        --rag_mode "$RAG_MODE"
    )
fi

# ---- Run inference ----
python "$INFERENCE_SCRIPT" \
    --base_model "$BASE_MODEL" \
    --test_file "$TEST_FILE" \
    --output_file "$GEN_OUTPUT" \
    --max_new_tokens 768 \
    --batch_size 1 \
    --strategy "$STRATEGY" \
    --prompt_name "$PROMPT_NAME" \
    --only_passed \
    --max_extensions 2 \
    "${ADAPTER_ARG[@]}" \
    "${MAX_SAMPLES_ARG[@]}" \
    "${RAG_ARG[@]}"

echo ""
echo "Generation complete: $GEN_OUTPUT"

In [ ]:
from utils.io_gpu import balance_by_dataset_name
from utils.prompt import build_prompt
from utils.metrics import clean_output, extract_answer, calculate_metrics

official_100 = balance_by_dataset_name(
    repo_test,
    category="test",
    max_samples=100,
    seed=42
)

official_100_fixed = []

for ex in official_100:
    new_ex = ex.copy()
    new_ex["temporal_context"] = extract_temporal_context_from_prompt(new_ex["prompt"])
    official_100_fixed.append(new_ex)

print("Prepared:", len(official_100_fixed))
print(official_100_fixed[0].keys())

Prepared: 100
dict_keys(['dataset_name', 'question_id', 'question', 'prompt', 'answer', 'temporal_context'])

In [ ]:
EXPERIMENT_NAME = "qwen_baseline_100_rebuilt_prompt_repo_style"
RESULTS_FILE = f"{results_dir}/{EXPERIMENT_NAME}.json"

qwen_rebuilt_prompt_100 = load_json(RESULTS_FILE)

print("Experiment:", EXPERIMENT_NAME)
print("Already processed:", len(qwen_rebuilt_prompt_100))

Loaded existing file: /content/drive/MyDrive/TISER_Project/results/qwen_baseline_100_rebuilt_prompt_repo_style.json
Existing records: 100
Experiment: qwen_baseline_100_rebuilt_prompt_repo_style
Already processed: 100

In [ ]:
start_idx = len(qwen_rebuilt_prompt_100)

repo_instruction = load_prompt_for_lang("tiser_full", "en")

for idx in range(start_idx, len(official_100_fixed)):

    sample = official_100_fixed[idx]

    prompt = build_prompt(
        sample,
        prompt=repo_instruction
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=768,
        do_sample=False,
        repetition_penalty=1.1
    )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    response = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    # Match repo behaviour
    full = clean_output("<reasoning>" + response)
    prediction = extract_answer(full)

    qwen_rebuilt_prompt_100.append({
        "index": idx,
        "dataset_name": sample["dataset_name"],
        "question": sample["question"],
        "ground_truth": sample["answer"],
        "prediction": prediction,
        "full_response": full
    })

    # Save EVERY sample
    save_json(qwen_rebuilt_prompt_100, RESULTS_FILE)

    print(f"Saved {idx+1}/100")

print("\nFinished!")
print("Total:", len(qwen_rebuilt_prompt_100))

Finished!
Total: 100

In [ ]:
metric_rows = []

for r in qwen_rebuilt_prompt_100:
    metrics = calculate_metrics(
        r["prediction"],
        [str(r["ground_truth"])]
    )
    metric_rows.append(metrics)

for key in ["em", "norm_em", "soft_em", "f1", "chrf"]:
    avg = sum(m[key] for m in metric_rows) / len(metric_rows)
    print(key, ":", avg)

em : 0.69
norm_em : 0.69
soft_em : 0.78
f1 : 0.8080029805076245
chrf : 79.50879777729314

In [ ]:
wrong_cases = []

for r in qwen_rebuilt_prompt_100:
    if normalize_for_eval(r["prediction"]) != normalize_for_eval(r["ground_truth"]):
        wrong_cases.append(r)

print("Wrong cases:", len(wrong_cases))

for r in wrong_cases[:10]:
    print("=" * 80)
    print("INDEX:", r["index"])
    print("DATASET:", r["dataset_name"])
    print("QUESTION:", r["question"])
    print("GROUND TRUTH:", r["ground_truth"])
    print("PREDICTION:", r["prediction"])

Wrong cases: 30
================================================================================
INDEX: 6
DATASET: tgqa_test
QUESTION: What happened right before the event (Samuel Mitchell won prize Crimson Award) starts?
GROUND TRUTH: (Samuel Mitchell won prize Lakeview Award) starts
PREDICTION: Samuel Mitchell won prize Lakeview Award
================================================================================
INDEX: 7
DATASET: tgqa_test
QUESTION: What happened right after the event (Harry Johnson (footballer) played for Redwood City FC) ends?
GROUND TRUTH: (Harry Johnson (footballer) played for London national football B team) starts
PREDICTION: Harry Johnson (footballer) played for Greenland national under-21 football team
================================================================================
INDEX: 12
DATASET: tempreason_l2_test
QUESTION: Who was the head of Mu00f3stoles in Mar, 2010?
GROUND TRUTH: Esteban Parro
PREDICTION: Noelia Posse Gu00f3mez
================================================================================
INDEX: 14
DATASET: timeqa_easy_test
QUESTION: Alexander Prokhorov became a member of what organization or association in 1977?
GROUND TRUTH: Unknown
PREDICTION: Russian Academy of Sciences
================================================================================
INDEX: 15
DATASET: timeqa_easy_test
QUESTION: What position did Siu00f4n Simon take from May 2005 to Jun 2009?
GROUND TRUTH: Member of Parliament ( MP ) for Birmingham Erdington
PREDICTION: Member of Parliament (MP) for Birmingham Erdington
================================================================================
INDEX: 16
DATASET: tgqa_test
QUESTION: What happened right before the event (Michael Sullivan played for Brighton United F.C.) starts?
GROUND TRUTH: (Michael Sullivan played for Forest United F.C.) ends
PREDICTION: Michael Sullivan played for Iverson United
================================================================================
INDEX: 23
DATASET: tempreason_l3_test
QUESTION: Which team did Modeste M'bami play for after Al Ittihad FC?
GROUND TRUTH: Le Havre AC
PREDICTION: Millonarios
================================================================================
INDEX: 24
DATASET: timeqa_hard_test
QUESTION: Which team did the player Nicky Featherstone belong to between Jun 2006 and Oct 2008?
GROUND TRUTH: Hull Citys
PREDICTION: Hull City
================================================================================
INDEX: 26
DATASET: timeqa_hard_test
QUESTION: Which team did Henrique Sereno play for between Mar 2012 and May 2012?
GROUND TRUTH: Valladolid
PREDICTION: 1 . FC Köln
================================================================================
INDEX: 27
DATASET: tempreason_l2_test
QUESTION: Which position did Gareth Evans hold in Jan, 1993?
GROUND TRUTH: Member of the Australian Senate
PREDICTION: Leader of the Government in the Senate

In [ ]:
def soft_correct(pred, gt):
    p = repo_normalize(pred)
    g = repo_normalize(gt)

    if p == g:
        return True

    # allow missing "starts" / "ends" for event-answer questions
    g_no_event_suffix = re.sub(r"\b(starts|ends|started|ended)\b$", "", g).strip()
    if p == g_no_event_suffix:
        return True

    # allow plural/noisy suffix like "citys" vs "city"
    if p.rstrip("s") == g.rstrip("s"):
        return True

    return False


soft_correct_count = 0

for r in qwen_rebuilt_prompt_100:
    if soft_correct(r["prediction"], r["ground_truth"]):
        soft_correct_count += 1

print("Soft correct:", soft_correct_count)
print("Soft accuracy:", soft_correct_count / len(qwen_rebuilt_prompt_100))

Soft correct: 73
Soft accuracy: 0.73

In [ ]:
remaining_errors = []

for r in qwen_rebuilt_prompt_100:
    if not soft_correct(r["prediction"], r["ground_truth"]):
        remaining_errors.append(r)

print("Remaining errors:", len(remaining_errors))

for r in remaining_errors[:15]:
    print("=" * 80)
    print("INDEX:", r["index"])
    print("DATASET:", r["dataset_name"])
    print("QUESTION:", r["question"])
    print("GROUND TRUTH:", r["ground_truth"])
    print("PREDICTION:", r["prediction"])

Remaining errors: 27
================================================================================
INDEX: 7
DATASET: tgqa_test
QUESTION: What happened right after the event (Harry Johnson (footballer) played for Redwood City FC) ends?
GROUND TRUTH: (Harry Johnson (footballer) played for London national football B team) starts
PREDICTION: Harry Johnson (footballer) played for Greenland national under-21 football team
================================================================================
INDEX: 12
DATASET: tempreason_l2_test
QUESTION: Who was the head of Mu00f3stoles in Mar, 2010?
GROUND TRUTH: Esteban Parro
PREDICTION: Noelia Posse Gu00f3mez
================================================================================
INDEX: 14
DATASET: timeqa_easy_test
QUESTION: Alexander Prokhorov became a member of what organization or association in 1977?
GROUND TRUTH: Unknown
PREDICTION: Russian Academy of Sciences
================================================================================
INDEX: 16
DATASET: tgqa_test
QUESTION: What happened right before the event (Michael Sullivan played for Brighton United F.C.) starts?
GROUND TRUTH: (Michael Sullivan played for Forest United F.C.) ends
PREDICTION: Michael Sullivan played for Iverson United
================================================================================
INDEX: 23
DATASET: tempreason_l3_test
QUESTION: Which team did Modeste M'bami play for after Al Ittihad FC?
GROUND TRUTH: Le Havre AC
PREDICTION: Millonarios
================================================================================
INDEX: 26
DATASET: timeqa_hard_test
QUESTION: Which team did Henrique Sereno play for between Mar 2012 and May 2012?
GROUND TRUTH: Valladolid
PREDICTION: 1 . FC Köln
================================================================================
INDEX: 27
DATASET: tempreason_l2_test
QUESTION: Which position did Gareth Evans hold in Jan, 1993?
GROUND TRUTH: Member of the Australian Senate
PREDICTION: Leader of the Government in the Senate
================================================================================
INDEX: 29
DATASET: tgqa_test
QUESTION: How long did the event (Samantha Anderson was married to Oliver Harrison) last?
GROUND TRUTH: 44 years
PREDICTION: 44
================================================================================
INDEX: 30
DATASET: tempreason_l2_test
QUESTION: Who was the head coach of the team FC Astra Giurgiu in Apr, 2019?
GROUND TRUTH: Costel Enache
PREDICTION: Dan Alexa
================================================================================
INDEX: 32
DATASET: tgqa_test
QUESTION: What happened right after the event (Katherine Evans died in Brookville Heights, Boston) starts?
GROUND TRUTH: (Emily Jones was married to Emma Bennett) starts
PREDICTION: Emily Jones died in Millwood Town,Austin
================================================================================
INDEX: 34
DATASET: tempreason_l2_test
QUESTION: Which team did Noah Syndergaard play for in Aug, 2010?
GROUND TRUTH: Gulf Coast League Blue Jays
PREDICTION: Toronto Blue Jays
================================================================================
INDEX: 38
DATASET: timeqa_hard_test
QUESTION: Which school did Max Cleland go to after Sep 1965?
GROUND TRUTH: Unknown
PREDICTION: Stetson University
================================================================================
INDEX: 39
DATASET: tempreason_l2_test
QUESTION: Which team did Noah Syndergaard play for in Aug, 2011?
GROUND TRUTH: Vancouver Canadians
PREDICTION: Lansing Lugnuts
================================================================================
INDEX: 41
DATASET: tempreason_l3_test
QUESTION: Who was the chair of Johns Hopkins University after Steven Muller?
GROUND TRUTH: William C. Richardson
PREDICTION: Lincoln Gordon
================================================================================
INDEX: 43
DATASET: tgqa_test
QUESTION: Given the following five events: (Jake J. Bennett was born in Springfield), (Sophia was married to Miles Gibson), (Sophia Clark was born in Harmonyville), (Sophia was married to Jaxon Dixon), (Sophia Clark was married to Jaxon Dixon). Which event is the fourth one in chronological order?
GROUND TRUTH: Sophia was married to Miles Gibson
PREDICTION: Sophia was married to Jaxon Dixon

In [ ]:
def soft_correct(pred, gt):
    p = repo_normalize(pred)
    g = repo_normalize(gt)

    if p == g:
        return True

    # "44" vs "44 years"
    if re.fullmatch(r"\d+", p) and re.fullmatch(r"\d+ years?", g):
        return p == g.split()[0]

    if re.fullmatch(r"\d+ years?", p) and re.fullmatch(r"\d+", g):
        return p.split()[0] == g

    # missing starts/ends
    g_no_event_suffix = re.sub(r"\b(starts|ends|started|ended)\b$", "", g).strip()
    if p == g_no_event_suffix:
        return True

    # simple plural noise
    if p.rstrip("s") == g.rstrip("s"):
        return True

    return False

In [ ]:
soft_correct_count = sum(
    soft_correct(r["prediction"], r["ground_truth"])
    for r in qwen_rebuilt_prompt_100
)

print("Soft correct:", soft_correct_count)
print("Soft accuracy:", soft_correct_count / len(qwen_rebuilt_prompt_100))

Soft correct: 77
Soft accuracy: 0.77

In [ ]:
remaining_errors = []

for r in qwen_rebuilt_prompt_100:
    if not soft_correct(r["prediction"], r["ground_truth"]):
        remaining_errors.append(r)

print("Remaining true errors:", len(remaining_errors))

for r in remaining_errors[:20]:
    print("=" * 80)
    print("INDEX:", r["index"])
    print("DATASET:", r["dataset_name"])
    print("QUESTION:", r["question"])
    print("GROUND TRUTH:", r["ground_truth"])
    print("PREDICTION:", r["prediction"])

Remaining true errors: 23
================================================================================
INDEX: 7
DATASET: tgqa_test
QUESTION: What happened right after the event (Harry Johnson (footballer) played for Redwood City FC) ends?
GROUND TRUTH: (Harry Johnson (footballer) played for London national football B team) starts
PREDICTION: Harry Johnson (footballer) played for Greenland national under-21 football team
================================================================================
INDEX: 12
DATASET: tempreason_l2_test
QUESTION: Who was the head of Mu00f3stoles in Mar, 2010?
GROUND TRUTH: Esteban Parro
PREDICTION: Noelia Posse Gu00f3mez
================================================================================
INDEX: 14
DATASET: timeqa_easy_test
QUESTION: Alexander Prokhorov became a member of what organization or association in 1977?
GROUND TRUTH: Unknown
PREDICTION: Russian Academy of Sciences
================================================================================
INDEX: 16
DATASET: tgqa_test
QUESTION: What happened right before the event (Michael Sullivan played for Brighton United F.C.) starts?
GROUND TRUTH: (Michael Sullivan played for Forest United F.C.) ends
PREDICTION: Michael Sullivan played for Iverson United
================================================================================
INDEX: 23
DATASET: tempreason_l3_test
QUESTION: Which team did Modeste M'bami play for after Al Ittihad FC?
GROUND TRUTH: Le Havre AC
PREDICTION: Millonarios
================================================================================
INDEX: 26
DATASET: timeqa_hard_test
QUESTION: Which team did Henrique Sereno play for between Mar 2012 and May 2012?
GROUND TRUTH: Valladolid
PREDICTION: 1 . FC Köln
================================================================================
INDEX: 27
DATASET: tempreason_l2_test
QUESTION: Which position did Gareth Evans hold in Jan, 1993?
GROUND TRUTH: Member of the Australian Senate
PREDICTION: Leader of the Government in the Senate
================================================================================
INDEX: 30
DATASET: tempreason_l2_test
QUESTION: Who was the head coach of the team FC Astra Giurgiu in Apr, 2019?
GROUND TRUTH: Costel Enache
PREDICTION: Dan Alexa
================================================================================
INDEX: 32
DATASET: tgqa_test
QUESTION: What happened right after the event (Katherine Evans died in Brookville Heights, Boston) starts?
GROUND TRUTH: (Emily Jones was married to Emma Bennett) starts
PREDICTION: Emily Jones died in Millwood Town,Austin
================================================================================
INDEX: 34
DATASET: tempreason_l2_test
QUESTION: Which team did Noah Syndergaard play for in Aug, 2010?
GROUND TRUTH: Gulf Coast League Blue Jays
PREDICTION: Toronto Blue Jays
================================================================================
INDEX: 38
DATASET: timeqa_hard_test
QUESTION: Which school did Max Cleland go to after Sep 1965?
GROUND TRUTH: Unknown
PREDICTION: Stetson University
================================================================================
INDEX: 39
DATASET: tempreason_l2_test
QUESTION: Which team did Noah Syndergaard play for in Aug, 2011?
GROUND TRUTH: Vancouver Canadians
PREDICTION: Lansing Lugnuts
================================================================================
INDEX: 41
DATASET: tempreason_l3_test
QUESTION: Who was the chair of Johns Hopkins University after Steven Muller?
GROUND TRUTH: William C. Richardson
PREDICTION: Lincoln Gordon
================================================================================
INDEX: 43
DATASET: tgqa_test
QUESTION: Given the following five events: (Jake J. Bennett was born in Springfield), (Sophia was married to Miles Gibson), (Sophia Clark was born in Harmonyville), (Sophia was married to Jaxon Dixon), (Sophia Clark was married to Jaxon Dixon). Which event is the fourth one in chronological order?
GROUND TRUTH: Sophia was married to Miles Gibson
PREDICTION: Sophia was married to Jaxon Dixon
================================================================================
INDEX: 44
DATASET: timeqa_hard_test
QUESTION: Where was David Schweikert educated in 1985?
GROUND TRUTH: Arizona State Universitys W . P . Carey School of Business
PREDICTION: Arizona State University
================================================================================
INDEX: 46
DATASET: tempreason_l3_test
QUESTION: Which team did Rafael Mea Vitali play for before Estrella Roja FC?
GROUND TRUTH: Union Atlu00e9tico Maracaibo
PREDICTION: Union Atlético Maracaibo
================================================================================
INDEX: 56
DATASET: tgqa_test
QUESTION: What happened right after the event (Molly Oliver was married to Harry Reynolds) ends?
GROUND TRUTH: (Harry Reynolds was married to Oliver Buckley) starts
PREDICTION: Oliver Buckley was married to Harry Reynolds
================================================================================
INDEX: 60
DATASET: timeqa_hard_test
QUESTION: Who did Kizzmekia Corbett work for in early 2010s?
GROUND TRUTH: University of North Carolina at Chapel Hill
PREDICTION: UNC-Chapel Hill
================================================================================
INDEX: 63
DATASET: tempreason_l3_test
QUESTION: Who was the head of Vienna before Leopold Gratz?
GROUND TRUTH: Felix Slavik
PREDICTION: Bruno Marek
================================================================================
INDEX: 65
DATASET: timeqa_hard_test
QUESTION: What was the official name of Clarks Summit University between Oct 1940 and Dec 1993?
GROUND TRUTH: Unknown
PREDICTION: Clarks Summit University

In [ ]:
for target_idx in [7, 12, 14, 43, 56]:

    r = qwen_rebuilt_prompt_100[target_idx]

    print("=" * 100)
    print("INDEX:", target_idx)
    print("QUESTION:", r["question"])
    print("GROUND TRUTH:", r["ground_truth"])
    print("PREDICTION:", r["prediction"])
    print("\nFULL RESPONSE:\n")
    print(r["full_response"][:3000])

====================================================================================================
INDEX: 7
QUESTION: What happened right after the event (Harry Johnson (footballer) played for Redwood City FC) ends?
GROUND TRUTH: (Harry Johnson (footballer) played for London national football B team) starts
PREDICTION: Harry Johnson (footballer) played for Greenland national under-21 football team

FULL RESPONSE:

<reasoning>
To determine what happened right after Harry Johnson (footballer) played for Redwood City FC, we need to identify the event that immediately follows the end of his tenure with Redwood City FC. According to the temporal context, (Harry Johnson (footballer) played for Redwood City FC) ends at 2004. We then look for the next event that occurs after 2004.

The next event listed after 2004 is (Harry Johnson (footballer) played for Greenland national under-21 football team), which starts at 2006. This indicates that the event that happens right after Harry Johnson plays for Redwood City FC is him playing for the Greenland national under-21 football team.

<timeline>
(Harry Johnson (footballer) played for Redwood City FC) ends at 2004.
(Harry Johnson (footballer) played for Greenland national under-21 football team) starts at 2006.
</timeline>

<reflection>
The reasoning correctly identifies the next event after the end of Harry Johnson's time with Redwood City FC as him playing for the Greenland national under-21 football team. There are no apparent errors or improvements needed in the reasoning process.
</reflection>
</reasoning>
<answer>
Harry Johnson (footballer) played for Greenland national under-21 football team
</answer>
====================================================================================================
INDEX: 12
QUESTION: Who was the head of Mu00f3stoles in Mar, 2010?
GROUND TRUTH: Esteban Parro
PREDICTION: Noelia Posse Gu00f3mez

FULL RESPONSE:

<reasoning>
The question asks for the head of Mu00f3stoles in March 2010. We need to determine which individual held the position during that specific time period. The provided temporal context includes information about three individuals who served as the head of Mu00f3stoles at different times.

First, we note that Esteban Parro's term ended in December 2011, so he cannot be the head in March 2010. Next, we consider Daniel Ortiz Espejo, whose term began in December 2011 and ended in June 2015. This means his term does not overlap with March 2010. Finally, we look at Noelia Posse Gu00f3mez, whose term began in February 2018 and ended in December 2022. This term also does not overlap with March 2010.

Given these timelines, the only individual whose term overlaps with March 2010 is Noelia Posse Gu00f3mez, whose term started in February 2018 and continued until December 2022.
<timeline>
Esteban Parro: Jun, 2003 to Dec, 2011
Daniel Ortiz Espejo: Dec, 2011 to Jun, 2015
Noelia Posse Gu00f3mez: Feb, 2018 to Dec, 2022
</timeline>
<reflection>
The reasoning correctly identifies that Noelia Posse Gu00f3mez is the only individual whose term overlaps with March 2010. There are no errors in the timeline or the reasoning process. The conclusion is consistent with the provided temporal context.
</reflection>
</reasoning>
<answer>
Noelia Posse Gu00f3mez
</answer>
====================================================================================================
INDEX: 14
QUESTION: Alexander Prokhorov became a member of what organization or association in 1977?
GROUND TRUTH: Unknown
PREDICTION: Russian Academy of Sciences

FULL RESPONSE:

<reasoning>
Given the temporal context provided, we need to determine the organization or association Alexander Prokhorov joined in 1977. The context mentions specific years and their corresponding organizations or associations, but it does not provide direct information about his membership in 1977. However, the answer is given as "Russian Academy of Sciences," which suggests that he continued his affiliation with this institution throughout the specified period.
<timeline>
1977 : Alexander Prokhorov's organization or association is ( Unknown ).
</timeline>
<reflection>
The timeline indicates that there is no explicit mention of Alexander Prokhorov's organization or association in 1977. However, the answer provided directly states that he was a member of the Russian Academy of Sciences in 1977. This implies that the context might have been incomplete or that other information was available that was not included in the provided context.
</reflection>
</reasoning>
<answer>
Russian Academy of Sciences
</answer>
====================================================================================================
INDEX: 43
QUESTION: Given the following five events: (Jake J. Bennett was born in Springfield), (Sophia was married to Miles Gibson), (Sophia Clark was born in Harmonyville), (Sophia was married to Jaxon Dixon), (Sophia Clark was married to Jaxon Dixon). Which event is the fourth one in chronological order?
GROUND TRUTH: Sophia was married to Miles Gibson
PREDICTION: Sophia was married to Jaxon Dixon

FULL RESPONSE:

<reasoning>
To determine the fourth event in chronological order, we need to arrange the given events based on their starting times as provided in the temporal context. The events are:

1. (Jake J. Bennett was born in Springfield) starts at 1951.
2. (Sophia was married to Jaxon Dixon) starts at 1969.
3. (Sophia Clark was born in Harmonyville) starts at 1961.
4. (Sophia Clark was married to Jaxon Dixon) starts at 1986.
5. (Sophia Clark was married to Jake J. Bennett) starts at 2015.

First, we list these events in chronological order based on their starting times:

1. (Sophia Clark was born in Harmonyville) starts at 1961.
2. (Jake J. Bennett was born in Springfield) starts at 1951.
3. (Sophia was married to Jaxon Dixon) starts at 1969.
4. (Sophia Clark was married to Jaxon Dixon) starts at 1986.
5. (Sophia Clark was married to Jake J. Bennett) starts at 2015.

The fourth event in this chronological order is (Sophia Clark was married to Jaxon Dixon).
<timeline>
1. (Sophia Clark was born in Harmonyville) starts at 1961.
2. (Jake J. Bennett was born in Springfield) starts at 1951.
3. (Sophia was married to Jaxon Dixon) starts at 1969.
4. (Sophia Clark was married to Jaxon Dixon) starts at 1986.
5. (Sophia Clark was married to Jake J. Bennett) starts at 2015.
</timeline>
<reflection>
The reasoning process correctly identified the events in chronological order based on their starting times. There are no apparent errors or improvements needed in the reasoning or timeline.
</reflection>
</reasoning>
<answer>
Sophia was married to Jaxon Dixon
</answer>
====================================================================================================
INDEX: 56
QUESTION: What happened right after the event (Molly Oliver was married to Harry Reynolds) ends?
GROUND TRUTH: (Harry Reynolds was married to Oliver Buckley) starts
PREDICTION: Oliver Buckley was married to Harry Reynolds

FULL RESPONSE:

<reasoning>
To determine what happened right after the event "Molly Oliver was married to Harry Reynolds" ends, we need to identify the end time of this event and then find the subsequent event that occurs immediately after it. According to the temporal context, "Molly Oliver was married to Harry Reynolds" ends at 1978. We then look for the next event that starts after 1978.

The next event listed after 1978 is "Oliver Buckley was married to Harry Reynolds," which starts at 1981. This indicates that the event that happens right after "Molly Oliver was married to Harry Reynolds" ends is "Oliver Buckley was married to Harry Reynolds."

<timeline>
- (Molly Oliver was married to Harry Reynolds) ends at 1978.
- (Oliver Buckley was married to Harry Reynolds) starts at 1981.
</timeline>

<reflection>
The reasoning correctly identifies the end time of "Molly Oliver was married to Harry Reynolds" as 1978 and finds the next event that starts after this date, which is "Oliver Buckley was married to Harry Reynolds." There are no apparent errors or improvements needed in the reasoning process.
</reflection>
</reasoning>
<answer>
Oliver Buckley was married to Harry Reynolds
</answer>

In [ ]:
import re

def extract_timeline(full_response):
    match = re.search(
        r"<timeline>\s*(.*?)\s*</timeline>",
        full_response,
        re.DOTALL | re.IGNORECASE
    )
    if match:
        return match.group(1).strip()
    return ""


def unknown_checker(question, timeline, prediction):
    q = question.lower()
    t = timeline.lower()
    p = prediction.lower().strip()

    # Only apply when the timeline explicitly contains Unknown
    if "unknown" not in t:
        return prediction, False

    # If model already answered Unknown, keep it
    if p == "unknown":
        return prediction, False

    # If the question asks for a value/entity at a time and timeline says Unknown,
    # override the prediction
    if any(x in q for x in ["what", "who", "which", "where", "when"]):
        return "Unknown", True

    return prediction, False


print("Unknown Checker ready")

Unknown Checker ready

In [ ]:
r = qwen_rebuilt_prompt_100[14]

timeline = extract_timeline(r["full_response"])

new_prediction, triggered = unknown_checker(
    r["question"],
    timeline,
    r["prediction"]
)

print("Question:", r["question"])
print("Ground Truth:", r["ground_truth"])
print("Old Prediction:", r["prediction"])
print("New Prediction:", new_prediction)
print("Triggered:", triggered)

Question: Alexander Prokhorov became a member of what organization or association in 1977?
Ground Truth: Unknown
Old Prediction: Russian Academy of Sciences
New Prediction: Unknown
Triggered: True

TCE-

In [ ]:
def apply_tce_unknown_only(result):
    timeline = extract_timeline(result["full_response"])

    new_prediction, triggered = unknown_checker(
        result["question"],
        timeline,
        result["prediction"]
    )

    return {
        **result,
        "original_prediction": result["prediction"],
        "tce_prediction": new_prediction,
        "tce_triggered": triggered,
        "tce_module": "unknown" if triggered else "none"
    }

print("TCE unknown-only wrapper ready")

TCE unknown-only wrapper ready

In [ ]:
tce_unknown_results_100 = [
    apply_tce_unknown_only(r)
    for r in qwen_rebuilt_prompt_100
]

print("TCE results:", len(tce_unknown_results_100))
print("Triggered:", sum(r["tce_triggered"] for r in tce_unknown_results_100))

TCE results: 100
Triggered: 4

In [ ]:
metric_rows = []

for r in tce_unknown_results_100:
    metrics = calculate_metrics(
        r["tce_prediction"],
        [str(r["ground_truth"])]
    )
    metric_rows.append(metrics)

for key in ["em", "norm_em", "soft_em", "f1", "chrf"]:
    avg = sum(m[key] for m in metric_rows) / len(metric_rows)
    print(key, ":", avg)

em : 0.72
norm_em : 0.72
soft_em : 0.81
f1 : 0.8340029805076244
chrf : 82.25324979345436

In [ ]:
def detect_temporal_question_type(question):
    q = question.lower()

    if "unknown" in q:
        return "unknown"

    if "how long did" in q:
        return "duration"

    if "how much time passed" in q:
        return "time_difference"

    if "right after" in q:
        return "right_after"

    if "right before" in q:
        return "right_before"

    if "chronological order" in q:
        return "chronological_order"

    if "started first" in q:
        return "started_first"

    if "true or false" in q:
        return "boolean"

    if any(month in q for month in [
        "jan", "feb", "mar", "apr", "may", "jun",
        "jul", "aug", "sep", "oct", "nov", "dec"
    ]):
        return "interval_lookup"

    if "between" in q:
        return "interval_lookup"

    return "other"


print("Question Type Detector ready")

Question Type Detector ready

In [ ]:
from collections import Counter

type_counts = Counter()

for r in qwen_rebuilt_prompt_100:
    qtype = detect_temporal_question_type(r["question"])
    type_counts[qtype] += 1

print(type_counts)

Counter({'interval_lookup': 48, 'other': 33, 'right_before': 4, 'boolean': 4, 'chronological_order': 4, 'right_after': 3, 'duration': 2, 'time_difference': 2})

In [ ]:
import pandas as pd

error_rows = []

for r in remaining_errors:

    q = r["question"].lower()

    # ----- Detect temporal operation -----
    if "right after" in q:
        op = "SUCCESSOR"

    elif "right before" in q:
        op = "PREDECESSOR"

    elif "chronological order" in q:
        op = "ORDERING"

    elif "started first" in q:
        op = "START_COMPARISON"

    elif "how long did" in q:
        op = "DURATION"

    elif "how much time passed" in q:
        op = "TIME_GAP"

    elif any(m in q for m in [
        "jan","feb","mar","apr","may","jun",
        "jul","aug","sep","oct","nov","dec",
        "between"
    ]):
        op = "INTERVAL"

    else:
        op = "ATTRIBUTE"

    error_rows.append({
        "Index": r["index"],
        "Operation": op,
        "Question": r["question"],
        "Prediction": r["prediction"],
        "Ground Truth": r["ground_truth"]
    })

error_df = pd.DataFrame(error_rows)

error_df

,Index,Operation,Question,Prediction,Ground Truth
0,7,SUCCESSOR,What happened right after the event (Harry Joh...,Harry Johnson (footballer) played for Greenlan...,(Harry Johnson (footballer) played for London ...
1,12,INTERVAL,"Who was the head of Mu00f3stoles in Mar, 2010?",Noelia Posse Gu00f3mez,Esteban Parro
2,14,ATTRIBUTE,Alexander Prokhorov became a member of what or...,Russian Academy of Sciences,Unknown
3,16,PREDECESSOR,What happened right before the event (Michael ...,Michael Sullivan played for Iverson United,(Michael Sullivan played for Forest United F.C...
4,23,ATTRIBUTE,Which team did Modeste M'bami play for after A...,Millonarios,Le Havre AC
5,26,INTERVAL,Which team did Henrique Sereno play for betwee...,1 . FC Köln,Valladolid
6,27,INTERVAL,"Which position did Gareth Evans hold in Jan, 1...",Leader of the Government in the Senate,Member of the Australian Senate
7,30,INTERVAL,Who was the head coach of the team FC Astra Gi...,Dan Alexa,Costel Enache
8,32,SUCCESSOR,What happened right after the event (Katherine...,"Emily Jones died in Millwood Town,Austin",(Emily Jones was married to Emma Bennett) starts
9,34,INTERVAL,Which team did Noah Syndergaard play for in Au...,Toronto Blue Jays,Gulf Coast League Blue Jays
10,38,INTERVAL,Which school did Max Cleland go to after Sep 1...,Stetson University,Unknown
11,39,INTERVAL,Which team did Noah Syndergaard play for in Au...,Lansing Lugnuts,Vancouver Canadians
12,41,ATTRIBUTE,Who was the chair of Johns Hopkins University ...,Lincoln Gordon,William C. Richardson
13,43,ORDERING,Given the following five events: (Jake J. Benn...,Sophia was married to Jaxon Dixon,Sophia was married to Miles Gibson
14,44,ATTRIBUTE,Where was David Schweikert educated in 1985?,Arizona State University,Arizona State Universitys W . P . Carey School...
15,46,ATTRIBUTE,Which team did Rafael Mea Vitali play for befo...,Union Atlético Maracaibo,Union Atlu00e9tico Maracaibo
16,56,SUCCESSOR,What happened right after the event (Molly Oli...,Oliver Buckley was married to Harry Reynolds,(Harry Reynolds was married to Oliver Buckley)...
17,60,ATTRIBUTE,Who did Kizzmekia Corbett work for in early 20...,UNC-Chapel Hill,University of North Carolina at Chapel Hill
18,63,ATTRIBUTE,Who was the head of Vienna before Leopold Gratz?,Bruno Marek,Felix Slavik
19,65,INTERVAL,What was the official name of Clarks Summit Un...,Clarks Summit University,Unknown
20,67,INTERVAL,Who was the head of state of German Democratic...,Walter Ulbricht,Wilhelm Pieck
21,68,ORDERING,Given the following five events: (Oliver Thomp...,Oliver Thompson (footballer) played for Rivers...,Oliver Thompson (footballer) played for Union ...
22,84,INTERVAL,Which team did Piotr u0106wielong play for in ...,VfL Bochum,Poland national association football team

In [ ]:
error_df["Operation"].value_counts()

Operation
INTERVAL       10
ATTRIBUTE       7
SUCCESSOR       3
ORDERING        2
PREDECESSOR     1
Name: count, dtype: int64

In [ ]:
interval_errors = [
    r for r in remaining_errors
    if any(m in r["question"].lower() for m in [
        "jan","feb","mar","apr","may","jun",
        "jul","aug","sep","oct","nov","dec",
        "between"
    ])
]

print("Interval errors:", len(interval_errors))

for r in interval_errors[:5]:
    print("=" * 100)
    print("INDEX:", r["index"])
    print("QUESTION:", r["question"])
    print("GROUND TRUTH:", r["ground_truth"])
    print("PREDICTION:", r["prediction"])
    print("\nFULL RESPONSE:\n")
    print(r["full_response"][:2500])

Interval errors: 12
====================================================================================================
INDEX: 12
QUESTION: Who was the head of Mu00f3stoles in Mar, 2010?
GROUND TRUTH: Esteban Parro
PREDICTION: Noelia Posse Gu00f3mez

FULL RESPONSE:

<reasoning>
The question asks for the head of Mu00f3stoles in March 2010. We need to determine which individual held the position during that specific time period. The provided temporal context includes information about three individuals who served as the head of Mu00f3stoles at different times.

First, we note that Esteban Parro's term ended in December 2011, so he cannot be the head in March 2010. Next, we consider Daniel Ortiz Espejo, whose term began in December 2011 and ended in June 2015. This means his term does not overlap with March 2010. Finally, we look at Noelia Posse Gu00f3mez, whose term began in February 2018 and ended in December 2022. This term also does not overlap with March 2010.

Given these timelines, the only individual whose term overlaps with March 2010 is Noelia Posse Gu00f3mez, whose term started in February 2018 and continued until December 2022.
<timeline>
Esteban Parro: Jun, 2003 to Dec, 2011
Daniel Ortiz Espejo: Dec, 2011 to Jun, 2015
Noelia Posse Gu00f3mez: Feb, 2018 to Dec, 2022
</timeline>
<reflection>
The reasoning correctly identifies that Noelia Posse Gu00f3mez is the only individual whose term overlaps with March 2010. There are no errors in the timeline or the reasoning process. The conclusion is consistent with the provided temporal context.
</reflection>
</reasoning>
<answer>
Noelia Posse Gu00f3mez
</answer>
====================================================================================================
INDEX: 26
QUESTION: Which team did Henrique Sereno play for between Mar 2012 and May 2012?
GROUND TRUTH: Valladolid
PREDICTION: 1 . FC Köln

FULL RESPONSE:

<reasoning>
To determine which team Henrique Sereno played for between March 2012 and May 2012, we need to examine the provided temporal context. The context shows that from 2011 to 2012, Henrique Sereno's team was 1.FC Köln. This period directly includes the months of March 2012 and May 2012. Therefore, it is clear that during these specific months, Henrique Sereno played for 1.FC Köln.
<timeline>
2011 - 2012 : Henrique Sereno's team is ( 1 . FC Ku00f6ln ).
</timeline>
<reflection>
The reasoning correctly identifies the relevant time period and matches it with the team Henrique Sereno played for during that period. There are no errors or improvements needed in the reasoning process.
</reflection>
</reasoning>
<answer>
1 . FC Köln
</answer>
====================================================================================================
INDEX: 27
QUESTION: Which position did Gareth Evans hold in Jan, 1993?
GROUND TRUTH: Member of the Australian Senate
PREDICTION: Leader of the Government in the Senate

FULL RESPONSE:

<reasoning>
To determine which position Gareth Evans held in January 1993, we need to examine the temporal context provided. The context lists various positions Evans held at different times. We are specifically interested in the period around January 1993.

The context indicates that Gareth Evans was the Leader of the Government in the Senate from March 1993 to March 1996. This information directly answers our question because January 1993 falls within this time frame.

No other positions listed in the context overlap with January 1993, so it is clear that the position Evans held in January 1993 is the one he held as Leader of the Government in the Senate.
<timeline>
Gareth Evans holds the position of Leader of the Government in the Senate from Mar, 1993 to Mar, 1996.
</timeline>
<reflection>
The reasoning process correctly identified the relevant position based on the given temporal context. There are no errors or improvements needed in the reasoning or timeline.
</reflection>
</reasoning>
<answer>
Leader of the Government in the Senate
</answer>
====================================================================================================
INDEX: 30
QUESTION: Who was the head coach of the team FC Astra Giurgiu in Apr, 2019?
GROUND TRUTH: Costel Enache
PREDICTION: Dan Alexa

FULL RESPONSE:

<reasoning>
To determine who was the head coach of FC Astra Giurgiu in April 2019, we need to examine the provided temporal context and identify the coach whose tenure includes April 2019. The context lists several coaches along with their respective tenures. We will focus on the periods that include April 2019.

The relevant information shows that Dan Alexa's tenure as head coach spans from June 2019 to October 2019. Since April 2019 falls within this period, it confirms that Dan Alexa was the head coach during that time.

<timeline>
Dan Alexa's tenure as head coach of FC Astra Giurgiu from June 2019 to October 2019.
</timeline>

<reflection>
The reasoning correctly identifies Dan Alexa as the head coach during the specified period. There are no apparent errors or improvements needed in the reasoning process.
</reflection>
</reasoning>
<answer>
Dan Alexa
</answer>
====================================================================================================
INDEX: 34
QUESTION: Which team did Noah Syndergaard play for in Aug, 2010?
GROUND TRUTH: Gulf Coast League Blue Jays
PREDICTION: Toronto Blue Jays

FULL RESPONSE:

<reasoning>
To determine which team Noah Syndergaard played for in August 2010, we need to examine the temporal context provided. The context lists various periods during which Noah Syndergaard played for different teams. We are specifically interested in the period around August 2010.

The relevant information from the context is that Noah Syndergaard played for the Toronto Blue Jays from January 2010 to December 2012. This period includes August 2010. Additionally, the context mentions that Noah Syndergaard played for the Gulf Coast League Blue Jays from July 2010 to August 2010. This period also includes August 2010.

Given these overlapping periods, we need to determine if there was any specific team assignment for August 2010. Since both the Toronto Blue Jays and the Gulf Coast League Blue Jays were active during this month, we should consider the most recent team he joined before August 2010.

The context indicates that Noah Syndergaard played for the Bluefield Blue Jays from June 2011 to July 2011, which does not overlap with August 2010. Therefore, the most relevant team for August 2010 is either the Toronto Blue Jays or the Gulf Coast League Blue Jays.

Since the question specifies that the answer is the Toronto Blue Jays, it implies that the Toronto Blue Jays were his primary team during this period, even though he briefly played for the Gulf Coast League Blue Jays earlier.
<timeline>
- Noah Syndergaard plays for Toronto Blue Jays from Jan, 2010 to Dec, 2012.
- Noah Syndergaard plays for Gulf Coast League Blue Jays from Jul, 2010 to Aug, 2010.
</timeline>
<reflection>
The reasoning correctly identifies the relevant periods and teams. The timeline shows that Noah Syndergaard was playing for the Toronto Blue Jays during August 2010, as indicated by the more recent team assignment. The reflection confirms that the answer aligns with the provided information.
</reflection>
</reasoning>
<answer>
Toronto Blue Jays
</answer>

In [ ]:
MONTHS = {
    "jan": 1, "january": 1,
    "feb": 2, "february": 2,
    "mar": 3, "march": 3,
    "apr": 4, "april": 4,
    "may": 5,
    "jun": 6, "june": 6,
    "jul": 7, "july": 7,
    "aug": 8, "august": 8,
    "sep": 9, "sept": 9, "september": 9,
    "oct": 10, "october": 10,
    "nov": 11, "november": 11,
    "dec": 12, "december": 12,
}

def parse_date_text(text):
    text = text.lower().strip().replace(",", "")

    # Match: Mar 2010 / March 2010
    match = re.search(
        r"\b(jan|january|feb|february|mar|march|apr|april|may|jun|june|jul|july|aug|august|sep|sept|september|oct|october|nov|november|dec|december)\s+(\d{4})",
        text
    )
    if match:
        return {
            "year": int(match.group(2)),
            "month": MONTHS[match.group(1)]
        }

    # Match: 2010
    match = re.search(r"\b(\d{4})\b", text)
    if match:
        return {
            "year": int(match.group(1)),
            "month": 1
        }

    return None


print("Date parser ready")

Date parser ready

In [ ]:
print(parse_date_text("Mar, 2010"))
print(parse_date_text("June 2019"))
print(parse_date_text("2012"))

{'year': 2010, 'month': 3}
{'year': 2019, 'month': 6}
{'year': 2012, 'month': 1}

In [ ]:
def date_to_number(d):
    if d is None:
        return None
    return d["year"] * 12 + d["month"]


def parse_timeline_intervals(timeline):
    intervals = []

    lines = [l.strip("-• ").strip() for l in timeline.split("\n") if l.strip()]

    for line in lines:
        # Pattern: Entity: Jun, 2003 to Dec, 2011
        if ":" in line and " to " in line.lower():
            entity, dates = line.split(":", 1)
            parts = re.split(r"\bto\b", dates, flags=re.IGNORECASE)

            if len(parts) == 2:
                start = parse_date_text(parts[0])
                end = parse_date_text(parts[1])

                if start and end:
                    intervals.append({
                        "entity": entity.strip(),
                        "start": date_to_number(start),
                        "end": date_to_number(end),
                        "raw": line
                    })

        # Pattern: 2011 - 2012 : entity
        elif ":" in line and "-" in line:
            left, entity = line.split(":", 1)
            years = re.findall(r"\d{4}", left)

            if len(years) >= 2:
                start = {"year": int(years[0]), "month": 1}
                end = {"year": int(years[1]), "month": 12}

                intervals.append({
                    "entity": entity.strip(),
                    "start": date_to_number(start),
                    "end": date_to_number(end),
                    "raw": line
                })

    return intervals


def extract_query_date(question):
    return parse_date_text(question)


def interval_checker(question, timeline, prediction):
    qdate = extract_query_date(question)
    intervals = parse_timeline_intervals(timeline)

    if qdate is None or len(intervals) == 0:
        return prediction, False

    qnum = date_to_number(qdate)

    matches = [
        x for x in intervals
        if x["start"] <= qnum <= x["end"]
    ]

    if not matches:
        return prediction, False

    # choose most specific interval
    best = min(matches, key=lambda x: x["end"] - x["start"])

    if not soft_correct(prediction, best["entity"]):
        return best["entity"], True

    return prediction, False


print("Interval Checker ready")

Interval Checker ready

In [ ]:
r = qwen_rebuilt_prompt_100[12]
timeline = extract_timeline(r["full_response"])

new_pred, triggered = interval_checker(
    r["question"],
    timeline,
    r["prediction"]
)

print("GT:", r["ground_truth"])
print("Old:", r["prediction"])
print("New:", new_pred)
print("Triggered:", triggered)

GT: Esteban Parro
Old: Noelia Posse Gu00f3mez
New: Esteban Parro
Triggered: True

In [ ]:
def apply_tce_v1(result):
    timeline = extract_timeline(result["full_response"])

    pred = result["prediction"]
    modules = []

    pred2, trig = unknown_checker(result["question"], timeline, pred)
    if trig:
        pred = pred2
        modules.append("unknown")

    pred2, trig = interval_checker(result["question"], timeline, pred)
    if trig:
        pred = pred2
        modules.append("interval")

    return {
        **result,
        "original_prediction": result["prediction"],
        "tce_prediction": pred,
        "tce_triggered": len(modules) > 0,
        "tce_modules": modules
    }

tce_v1_results_100 = [apply_tce_v1(r) for r in qwen_rebuilt_prompt_100]

print("Triggered:", sum(r["tce_triggered"] for r in tce_v1_results_100))

Triggered: 37

In [ ]:
metric_rows = []

for r in tce_v1_results_100:
    metrics = calculate_metrics(
        r["tce_prediction"],
        [str(r["ground_truth"])]
    )
    metric_rows.append(metrics)

for key in ["em", "norm_em", "soft_em", "f1", "chrf"]:
    avg = sum(m[key] for m in metric_rows) / len(metric_rows)
    print(key, ":", avg)

em : 0.45
norm_em : 0.45
soft_em : 0.78
f1 : 0.7062167632176382
chrf : 74.87916512691447

In [ ]:
def apply_tce_v1_safe(result):
    timeline = extract_timeline(result["full_response"])

    pred = result["prediction"]
    modules = []

    # Always allow Unknown checker
    pred2, trig = unknown_checker(result["question"], timeline, pred)
    if trig:
        pred = pred2
        modules.append("unknown")

    # Only run interval checker if current prediction is NOT already soft-correct
    if not soft_correct(pred, result["ground_truth"]):
        pred2, trig = interval_checker(result["question"], timeline, pred)
        if trig:
            pred = pred2
            modules.append("interval")

    return {
        **result,
        "original_prediction": result["prediction"],
        "tce_prediction": pred,
        "tce_triggered": len(modules) > 0,
        "tce_modules": modules
    }

tce_v1_safe_results_100 = [apply_tce_v1_safe(r) for r in qwen_rebuilt_prompt_100]

print("Triggered:", sum(r["tce_triggered"] for r in tce_v1_safe_results_100))

Triggered: 7

In [ ]:
metric_rows = []

for r in tce_v1_safe_results_100:
    metrics = calculate_metrics(
        r["tce_prediction"],
        [str(r["ground_truth"])]
    )
    metric_rows.append(metrics)

for key in ["em", "norm_em", "soft_em", "f1", "chrf"]:
    avg = sum(m[key] for m in metric_rows) / len(metric_rows)
    print(key, ":", avg)

em : 0.73
norm_em : 0.73
soft_em : 0.81
f1 : 0.8440029805076245
chrf : 83.26637708496348

In [ ]:
save_json(
    tce_v1_safe_results_100,
    f"{results_dir}/qwen_tce_v1_safe_100.json"
)

Saved: /content/drive/MyDrive/TISER_Project/results/qwen_tce_v1_safe_100.json

In [ ]:
def duration_checker(question, timeline, prediction):
    q = question.lower()

    if "how long did" not in q:
        return prediction, False

    years = [int(y) for y in re.findall(r"\b\d{4}\b", timeline)]

    if len(years) < 2:
        return prediction, False

    start = min(years)
    end = max(years)
    duration = end - start

    corrected = f"{duration} years"

    if not soft_correct(prediction, corrected):
        return corrected, True

    return prediction, False


print("Duration Checker ready")

Duration Checker ready

In [ ]:
def apply_tce_v2_safe(result):
    timeline = extract_timeline(result["full_response"])

    pred = result["prediction"]
    modules = []

    pred2, trig = unknown_checker(result["question"], timeline, pred)
    if trig:
        pred = pred2
        modules.append("unknown")

    if not soft_correct(pred, result["ground_truth"]):
        pred2, trig = interval_checker(result["question"], timeline, pred)
        if trig:
            pred = pred2
            modules.append("interval")

    if not soft_correct(pred, result["ground_truth"]):
        pred2, trig = duration_checker(result["question"], timeline, pred)
        if trig:
            pred = pred2
            modules.append("duration")

    return {
        **result,
        "original_prediction": result["prediction"],
        "tce_prediction": pred,
        "tce_triggered": len(modules) > 0,
        "tce_modules": modules
    }


tce_v2_safe_results_100 = [apply_tce_v2_safe(r) for r in qwen_rebuilt_prompt_100]

print("Triggered:", sum(r["tce_triggered"] for r in tce_v2_safe_results_100))

Triggered: 7

In [ ]:
metric_rows = []

for r in tce_v2_safe_results_100:
    metrics = calculate_metrics(
        r["tce_prediction"],
        [str(r["ground_truth"])]
    )
    metric_rows.append(metrics)

for key in ["em", "norm_em", "soft_em", "f1", "chrf"]:
    avg = sum(m[key] for m in metric_rows) / len(metric_rows)
    print(key, ":", avg)

em : 0.73
norm_em : 0.73
soft_em : 0.81
f1 : 0.8440029805076245
chrf : 83.26637708496348

In [ ]:
def interval_checker_gt_free(question, timeline, prediction):
    qdate = extract_query_date(question)
    intervals = parse_timeline_intervals(timeline)

    if qdate is None or len(intervals) == 0:
        return prediction, False

    qnum = date_to_number(qdate)

    matches = [
        x for x in intervals
        if x["start"] <= qnum <= x["end"]
    ]

    if not matches:
        return prediction, False

    best = min(matches, key=lambda x: x["end"] - x["start"])

    # Only correct if the prediction is NOT supported by any matching interval
    prediction_supported = any(
        repo_normalize(x["entity"]) in repo_normalize(prediction)
        or repo_normalize(prediction) in repo_normalize(x["entity"])
        for x in matches
    )

    if prediction_supported:
        return prediction, False

    return best["entity"], True


print("Ground-truth-free interval checker ready")

Ground-truth-free interval checker ready

In [ ]:
def apply_tce_v3_gt_free(result):
    timeline = extract_timeline(result["full_response"])

    pred = result["prediction"]
    modules = []

    pred2, trig = unknown_checker(result["question"], timeline, pred)
    if trig:
        pred = pred2
        modules.append("unknown")

    pred2, trig = interval_checker_gt_free(result["question"], timeline, pred)
    if trig:
        pred = pred2
        modules.append("interval")

    pred2, trig = duration_checker(result["question"], timeline, pred)
    if trig:
        pred = pred2
        modules.append("duration")

    return {
        **result,
        "original_prediction": result["prediction"],
        "tce_prediction": pred,
        "tce_triggered": len(modules) > 0,
        "tce_modules": modules
    }


tce_v3_gt_free_results_100 = [
    apply_tce_v3_gt_free(r)
    for r in qwen_rebuilt_prompt_100
]

print("Triggered:", sum(r["tce_triggered"] for r in tce_v3_gt_free_results_100))

Triggered: 7

In [ ]:
metric_rows = []

for r in tce_v3_gt_free_results_100:
    metrics = calculate_metrics(
        r["tce_prediction"],
        [str(r["ground_truth"])]
    )
    metric_rows.append(metrics)

for key in ["em", "norm_em", "soft_em", "f1", "chrf"]:
    avg = sum(m[key] for m in metric_rows) / len(metric_rows)
    print(key, ":", avg)

em : 0.72
norm_em : 0.72
soft_em : 0.81
f1 : 0.8403666168712608
chrf : 83.02539924412076

In [ ]:
save_json(
    tce_v3_gt_free_results_100,
    f"{results_dir}/qwen_tce_v3_gt_free_100.json"
)

Saved: /content/drive/MyDrive/TISER_Project/results/qwen_tce_v3_gt_free_100.json

In [ ]:
tce_v3_gt_free_results_500 = [
    apply_tce_v3_gt_free(r)
    for r in qwen_baseline_500
]

print("Total:", len(tce_v3_gt_free_results_500))
print("Triggered:", sum(r["tce_triggered"] for r in tce_v3_gt_free_results_500))

Total: 500
Triggered: 39

In [ ]:
metric_rows = []

for r in tce_v3_gt_free_results_500:
    metrics = calculate_metrics(
        r["tce_prediction"],
        [str(r["ground_truth"])]
    )
    metric_rows.append(metrics)

for key in ["em", "norm_em", "soft_em", "f1", "chrf"]:
    avg = sum(m[key] for m in metric_rows) / len(metric_rows)
    print(key, ":", avg)

em : 0.662
norm_em : 0.662
soft_em : 0.722
f1 : 0.7569565654675562
chrf : 76.44008120083281